import { Link } from "react-router-dom";
import { Star } from "lucide-react";
import type { CatalogItem } from "@/lib/documents";
import { coverArt } from "@/lib/cover-art";
import BookCover from "@/components/home/BookCover";

const priceLabel = (c: number) => (c > 0 ? `$${(c / 100).toFixed(2)}` : "Free");
const isNew = (d: string) => { const days = (Date.now() - new Date(d).getTime()) / 86_400_000; return days >= 0 && days <= 14; };

// A storefront cover tile — the marketplace's atom. Renders the shared, now
// category-aware BookCover (literary / academic / playful treatments) and
// overlays the real price, rank and badges, so the shelf reads like a
// publisher's list, not autogenerated tiles.
const ShelfCard = ({ item: it, rank }: { item: CatalogItem; rank?: number }) => {
  const { from, to } = coverArt(`${it.title}·${it.category ?? ""}`);
  return (
    <Link to={`/shared/${it.token}`} className="group block w-[148px] shrink-0 snap-start sm:w-[166px]">
      <div className="relative transition-transform duration-300 group-hover:-translate-y-1.5">
        <BookCover spec={{ title: it.title, author: it.author_name ?? "", from, to, tag: it.category ?? undefined }} />
        <span className="absolute left-1.5 top-1.5 z-20 rounded bg-black/55 px-1.5 py-0.5 text-[9px] font-bold text-white backdrop-blur-sm">{priceLabel(it.price_cents)}</span>
        <div className="absolute right-1.5 top-1.5 z-20 flex gap-1">
          {rank != null && <span className="rounded bg-white/90 px-1.5 py-0.5 text-[9px] font-extrabold text-slate-900">#{rank}</span>}
          {it.featured && <span className="rounded bg-gold px-1.5 py-0.5 text-[9px] font-bold text-white">★</span>}
          {!it.featured && isNew(it.created_at) && <span className="rounded bg-educational px-1.5 py-0.5 text-[9px] font-bold text-white">New</span>}
        </div>
      </div>

      {(it.review_count ?? 0) > 0 && it.avg_rating != null ? (
        <div className="mt-1.5 flex items-center gap-1 px-0.5">
          <Star className="h-3 w-3 fill-gold text-gold" />
          <span className="font-sans text-[10px] text-muted-foreground">{Number(it.avg_rating).toFixed(1)} · {it.review_count}</span>
        </div>
      ) : (
        <div className="mt-1.5 truncate px-0.5 font-sans text-[10px] text-muted-foreground group-hover:text-primary">{it.author_name ? `by ${it.author_name}` : "View listing"}</div>
      )}
    </Link>
  );
};

export default ShelfCard;
