-- 0012 — Reposition CIVICOS as Sovereign Operating Infrastructure and add its
-- deployable module suite (National Shell, Coordination Engine, TreasuryOS,
-- HealthOS, JusticeOS, EducationOS, TransportOS, EmergencyOS, PoliceOS,
-- Anti-Corruption Intelligence OS) to the ecosystem catalogue.

update ecosystem_products set
  name='CIVICOS',
  category='Sovereign Operating Infrastructure',
  tagline='A deployable government operating system for the modern state.',
  description='Sovereign operational infrastructure — a national runtime binding ministries, treasury, justice, health, emergency and oversight into one AI-governed operating system, deployable as state capability.',
  capabilities='["National Shell","National Coordination Engine","Interoperability fabric","National digital twin","Executive AI command","Anti-corruption intelligence"]'::jsonb,
  metrics='[{"label":"Deployment value","value":"$500M–$3B"},{"label":"OS modules","value":"10+"},{"label":"Coordination","value":"Whole-of-gov"}]'::jsonb,
  accent='#6366F1', updated_at=now()
where slug='civicos';

insert into ecosystem_products (slug, name, category, tagline, description, capabilities, metrics, accent, sort_order, status) values
('civicos-national-shell','National Shell','Sovereign Government Runtime','The sovereign orchestration layer binding government into one runtime.','Executive orchestration, institutional topology and cross-ministry propagation as a single national operating runtime.','["Executive orchestration","Cross-ministry propagation","Runtime governance","National posture intelligence"]'::jsonb,'[{"label":"Deployment value","value":"$300M–$500M"},{"label":"Strategic value","value":"Extreme"},{"label":"Scope","value":"Whole-of-gov"}]'::jsonb,'#6366F1',51,'deployable'),
('civicos-coordination-engine','National Coordination Engine','Government Coordination Infrastructure','Cross-government dependency and institutional coordination.','Ministry dependency intelligence, cascade modeling and national execution logic synchronising the whole of government.','["Ministry dependency intelligence","Cascade modeling","National execution logic","Operational synchronization"]'::jsonb,'[{"label":"Deployment value","value":"$100M–$300M"},{"label":"Strategic value","value":"Extreme"},{"label":"Function","value":"Cascade modeling"}]'::jsonb,'#00C2FF',52,'deployable'),
('civicos-treasury','TreasuryOS','Sovereign Government Treasury','Sovereign financial orchestration infrastructure.','Treasury runtime, national liquidity intelligence and fiscal command systems for the sovereign state.','["Treasury runtime","National liquidity intelligence","Budget coordination","Fiscal command systems"]'::jsonb,'[{"label":"Deployment value","value":"$50M–$120M"},{"label":"Strategic value","value":"Very high"},{"label":"Function","value":"Fiscal command"}]'::jsonb,'#10B981',53,'deployable'),
('civicos-health','HealthOS','Government Health Infrastructure','National healthcare operational runtime.','Hospital orchestration, national health telemetry and crisis healthcare propagation across the state.','["Hospital orchestration","Emergency capacity intelligence","National health telemetry","Public health AI"]'::jsonb,'[{"label":"Deployment value","value":"$35M–$80M"},{"label":"Strategic value","value":"High"},{"label":"Function","value":"Health runtime"}]'::jsonb,'#22D3EE',54,'deployable'),
('civicos-justice','JusticeOS','Government Justice Infrastructure','Judicial and constitutional operational infrastructure.','Court orchestration, judicial intelligence and constitutional continuity for the sovereign judiciary.','["Court orchestration","Constitutional workflow","Judicial intelligence","Constitutional continuity"]'::jsonb,'[{"label":"Deployment value","value":"$30M–$70M"},{"label":"Strategic value","value":"High"},{"label":"Function","value":"Judicial runtime"}]'::jsonb,'#7C4DFF',55,'deployable'),
('civicos-education','EducationOS','Government Education Infrastructure','National education coordination infrastructure.','National academic runtime, institution orchestration and AI learning governance at national scale.','["National academic runtime","Institution orchestration","Educational telemetry","AI learning governance"]'::jsonb,'[{"label":"Deployment value","value":"$30M–$60M"},{"label":"Strategic value","value":"High"},{"label":"Function","value":"Education runtime"}]'::jsonb,'#06B6D4',56,'deployable'),
('civicos-transport','TransportOS','Government Transport Infrastructure','National transport and mobility orchestration.','National mobility coordination, logistics intelligence and strategic mobility systems.','["National mobility coordination","Logistics intelligence","Emergency routing","Strategic mobility systems"]'::jsonb,'[{"label":"Deployment value","value":"$45M–$100M"},{"label":"Strategic value","value":"High"},{"label":"Function","value":"Mobility runtime"}]'::jsonb,'#F59E0B',57,'deployable'),
('civicos-emergency','EmergencyOS','Government Emergency Infrastructure','National emergency response and crisis coordination runtime.','Disaster coordination, crisis propagation modeling and multi-agency emergency command.','["Disaster coordination","Crisis propagation modeling","Emergency command","Multi-agency coordination"]'::jsonb,'[{"label":"Deployment value","value":"$70M–$200M"},{"label":"Strategic value","value":"Very high"},{"label":"Function","value":"Crisis command"}]'::jsonb,'#FF5470',58,'deployable'),
('civicos-police','PoliceOS','Government Public Safety Infrastructure','National law enforcement operational infrastructure.','National policing coordination, criminal intelligence workflows and public safety telemetry.','["National policing coordination","Incident intelligence","Tactical coordination","Public safety telemetry"]'::jsonb,'[{"label":"Deployment value","value":"$60M–$180M"},{"label":"Strategic value","value":"High"},{"label":"Function","value":"Safety runtime"}]'::jsonb,'#3B82F6',59,'deployable'),
('civicos-anti-corruption','Anti-Corruption Intelligence OS','Government Anti-Corruption Intelligence','AI-native anti-corruption operational intelligence.','Procurement anomaly detection, cross-ministry financial tracing and AI fraud investigation for national transparency.','["Procurement anomaly detection","Institutional audit chains","Risk propagation analysis","Cross-ministry financial tracing"]'::jsonb,'[{"label":"Deployment value","value":"$80M–$250M"},{"label":"Strategic value","value":"Very high"},{"label":"Function","value":"Forensic AI"}]'::jsonb,'#FFB547',60,'deployable')
on conflict (slug) do update set
  name=excluded.name, category=excluded.category, tagline=excluded.tagline, description=excluded.description,
  capabilities=excluded.capabilities, metrics=excluded.metrics, accent=excluded.accent, sort_order=excluded.sort_order, updated_at=now();
