// Refresh script for src/buyers/history.ts.
//
// Runs the EDGAR and Wikidata adapters against the configured buyer
// list, merges the results into the canonical AcquisitionEvent shape,
// and writes back to src/buyers/history.ts as a TypeScript module so
// the engine remains build-time deterministic.
//
// Usage:
//   cd services/exit-engines
//   npm run build
//   USER_AGENT='ExitOS/0.1 (icofcucam@gmail.com)' \
//     node dist/scripts/refresh-buyer-history.js
//
// Network policy: requires data.sec.gov, www.sec.gov, efts.sec.gov,
// and query.wikidata.org to be reachable. This remote-execution
// environment blocks all four by default — run it from an environment
// where they are allowed.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  EDGAR_BUYER_CIKS, fetchEdgar8KFilings, extractAcquisitionFromFiling,
  type EdgarConfig,
} from '../buyers/edgar.js';
import {
  WIKIDATA_BUYER_QIDS, fetchWikidataAcquisitions,
  type WikidataConfig,
} from '../buyers/wikidata.js';
import type { AcquisitionEvent } from '../buyers/history-types.js';

async function main(): Promise<void> {
  const userAgent = process.env.USER_AGENT;
  if (!userAgent) {
    console.error('USER_AGENT env var required (SEC EDGAR mandates it).');
    process.exit(1);
  }

  const edgarConfig:    EdgarConfig    = { userAgent, throttleMs: 120 };
  const wikidataConfig: WikidataConfig = { userAgent };

  const since = new Date(Date.now() - 365 * 4 * 86_400_000).toISOString();
  const events: AcquisitionEvent[] = [];

  // EDGAR ─ 8-K material agreements (Items 1.01 / 2.01)
  for (const buyer of EDGAR_BUYER_CIKS) {
    console.log(`EDGAR · ${buyer.buyerName} (CIK ${buyer.cik})`);
    try {
      const filings = await fetchEdgar8KFilings(buyer, edgarConfig, since);
      for (const filing of filings) {
        const event = await extractAcquisitionFromFiling(filing, edgarConfig);
        if (event) events.push(event);
      }
    } catch (err) {
      console.warn(`  skipped: ${(err as Error).message}`);
    }
  }

  // Wikidata ─ P749 (parent organization) relationships
  for (const buyer of WIKIDATA_BUYER_QIDS) {
    console.log(`Wikidata · ${buyer.buyerName} (${buyer.qid})`);
    try {
      const results = await fetchWikidataAcquisitions(buyer, wikidataConfig);
      events.push(...results);
    } catch (err) {
      console.warn(`  skipped: ${(err as Error).message}`);
    }
  }

  // Deduplicate by (buyerName, targetName, announcedDate)
  const seen = new Map<string, AcquisitionEvent>();
  for (const e of events) {
    const key = `${e.buyerName}|${e.targetName}|${e.announcedDate.slice(0, 7)}`;
    const prior = seen.get(key);
    if (!prior) {
      seen.set(key, e);
      continue;
    }
    // Merge source refs from duplicate
    seen.set(key, {
      ...prior,
      ...(e.headlinePriceUsd && !prior.headlinePriceUsd ? { headlinePriceUsd: e.headlinePriceUsd } : {}),
      sourceRefs: [...prior.sourceRefs, ...e.sourceRefs],
    });
  }

  const merged = Array.from(seen.values()).sort(
    (a, b) => new Date(b.announcedDate).getTime() - new Date(a.announcedDate).getTime(),
  );

  const here = dirname(fileURLToPath(import.meta.url));
  const out = resolve(here, '../../src/buyers/history.ts');
  const banner = `// AUTOGENERATED by scripts/refresh-buyer-history.ts on ${new Date().toISOString()}\n// Re-run when EDGAR/Wikidata coverage advances.\nimport type { AcquisitionEvent } from './history-types.js';\n\nexport const ACQUISITION_HISTORY: readonly AcquisitionEvent[] = ${JSON.stringify(merged, null, 2)};\n`;
  writeFileSync(out, banner);
  console.log(`\nWrote ${merged.length} events to ${out}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
