// A broad, international list of countries for curriculum/cultural-setting
// fields, with the United States first as the neutral default. The fields stay
// free-text (so "US Common Core", "IB", a region, etc. are all valid) — this
// just powers a dropdown of suggestions so no single region is the implied
// default.
export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Ireland",
  "Germany",
  "France",
  "Spain",
  "Portugal",
  "Italy",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Czech Republic",
  "Greece",
  "Turkey",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "India",
  "China",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Brazil",
  "Mexico",
  "Argentina",
  "Chile",
  "Colombia",
  "South Africa",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Morocco",
  "New Zealand",
];
