import React, { useMemo, useState } from "react";
import { Button, Card, Kpi, SectionHeader } from "../lib/ui";
import { BUYERS, useMemorandum } from "../lib/engines";

// Banker AI — a virtual investment banker. Drafts the outreach sequence,
// generates buyer introductions from the discovery engine, and produces the
// teaser / executive summary via the memorandum engine. Outputs are deal
// collateral, ready for the founder to review and send.

type Tab = "outreach" | "intros" | "teaser" | "summary";

const Banker: React.FC = () => {
  const [tab, setTab] = useState<Tab>("outreach");
  const teaser = useMemorandum("buyer_teaser");
  const summary = useMemorandum("executive_summary");
  const topBuyers = useMemo(() => BUYERS.candidates.slice(0, 6), []);

  return (
    <div>
      <SectionHeader
        kicker="Module · Operator"
        title="Banker AI"
        description="Your virtual investment banker. Generates the outreach campaign, drafts buyer introductions, and produces the teaser and executive summary — automatically, from the company profile and buyer-discovery engine."
        actions={<Button>Launch outreach</Button>}
      />

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <Kpi label="Buyers matched" value={String(BUYERS.candidates.length)} sub="ranked by fit" accent="#34d399" />
        <Kpi label="Outreach steps" value={String(SEQUENCE.length)} sub="campaign sequence" />
        <Kpi label="Teaser" value={teaser ? `${teaser.wordCount}w` : "—"} sub="anonymized · pre-NDA" />
        <Kpi label="Exec summary" value={summary ? `${summary.wordCount}w` : "—"} sub="one-pager" />
      </div>

      <div className="mt-8 flex flex-wrap gap-2">
        {([["outreach", "Outreach campaign"], ["intros", "Buyer introductions"], ["teaser", "Teaser"], ["summary", "Executive summary"]] as [Tab, string][]).map(([k, l]) => (
          <button key={k} onClick={() => setTab(k)} className={`rounded-md px-3.5 py-2 text-[13px] font-semibold transition ${tab === k ? "bg-deal-600/20 text-white ring-1 ring-deal-400/40" : "text-white/60 hover:bg-white/5 hover:text-white"}`}>{l}</button>
        ))}
      </div>

      <div className="mt-6">
        {tab === "outreach" && (
          <div className="space-y-2">
            {SEQUENCE.map((s, i) => (
              <Card key={s.step} className="flex items-start gap-4 p-4">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-deal-600/20 font-mono text-[12px] font-bold text-deal-200 ring-1 ring-deal-400/40">{i + 1}</span>
                <div className="flex-1">
                  <div className="flex items-center justify-between">
                    <div className="text-sm font-bold text-white">{s.step}</div>
                    <div className="text-[11px] text-white/40">{s.timing}</div>
                  </div>
                  <div className="mt-0.5 text-[12px] leading-snug text-white/60">{s.body}</div>
                </div>
              </Card>
            ))}
          </div>
        )}

        {tab === "intros" && (
          <div className="grid gap-3 sm:grid-cols-2">
            {topBuyers.map((b) => (
              <Card key={b.buyer.name} className="p-4">
                <div className="flex items-center justify-between">
                  <div className="text-sm font-bold text-white">{b.buyer.name}</div>
                  <span className="font-mono text-[13px] font-bold text-deal-300">{Math.round(b.probability * 100)}%</span>
                </div>
                <div className="text-[11px] text-white/45">{b.buyer.buyerType.replace(/_/g, " ")}</div>
                <p className="mt-2 text-[12px] leading-relaxed text-white/70">
                  Suggested intro: position {teaser ? "Project Cipher" : "the company"} to {b.buyer.name} — {b.rationale}
                </p>
                <Button variant="ghost" className="mt-3 text-[12px]">Draft introduction</Button>
              </Card>
            ))}
          </div>
        )}

        {(tab === "teaser" || tab === "summary") && (() => {
          const doc = tab === "teaser" ? teaser : summary;
          if (!doc) return <Card className="p-6 text-sm text-white/40">Generating…</Card>;
          return (
            <Card className="p-7">
              <div className="text-[10px] font-semibold uppercase tracking-[0.24em] text-deal-400">Generated by {doc.producedBy}</div>
              <h2 className="mt-2 font-serif text-2xl font-bold text-white">{doc.title}</h2>
              <div className="mt-1 text-[11px] text-white/45">{doc.sections.length} sections · {doc.wordCount} words{doc.anonymized ? " · anonymized" : ""}</div>
              <div className="mt-5 space-y-5">
                {doc.sections.map((s, i) => (
                  <section key={`${i}-${s.heading}`}>
                    <h3 className="font-serif text-base font-bold text-white">{s.heading}</h3>
                    <p className="mt-1.5 text-[13px] leading-relaxed text-white/70">{s.body}</p>
                  </section>
                ))}
              </div>
            </Card>
          );
        })()}
      </div>
    </div>
  );
};

const SEQUENCE = [
  { step: "Build target list", timing: "Day 0", body: "Rank acquirers by fit, appetite and recent activity; segment strategic vs financial." },
  { step: "Issue anonymized teaser", timing: "Day 1", body: "Send Project Cipher teaser to tier-1 targets; no company name pre-NDA." },
  { step: "NDA + data room", timing: "Day 3–7", body: "Counter-sign NDAs, grant staged data-room access on execution." },
  { step: "Management presentations", timing: "Week 2–3", body: "Schedule calls with engaged buyers; distribute the CIM." },
  { step: "Solicit indications", timing: "Week 4", body: "Request non-binding indications of interest; build the offer comparison." },
  { step: "Drive to LOI", timing: "Week 5–6", body: "Run a competitive process to a signed letter of intent." },
];

export default Banker;
