// Layer 2 of the SEO ecosystem — Industry Landing Pages. One substantive page per
// institution type, each explaining Sovereign Dispatch in that sector's own
// language: the official publications it issues, the authorities that govern
// them, the sector's specific failure modes, and the frameworks it is assessed
// against. These are NOT thin doorway pages — each is a real reference, written
// to be cited by search engines AND by AI answer engines (Perplexity, ChatGPT,
// Claude, Gemini). The engine scales to 50+; this is the founding set.

export interface Industry {
  slug: string;
  name: string;              // "Government"
  forLabel: string;          // "for Government" (used in titles/URLs reasoning)
  banner: string;            // an existing /banners or /people image slug
  headline: string;          // the sector-specific promise
  intro: string;             // 1–2 sentences, what governed publication means here
  publications: string[];    // the official documents this sector issues
  authorities: string[];     // the offices/roles that govern them
  problems: { t: string; d: string }[]; // sector-specific governance failure modes
  frameworks: string[];      // standards / regulations this sector is held to
  metaTitle: string;
  metaDescription: string;
}

export const INDUSTRIES: Industry[] = [
  {
    slug: "government",
    name: "Government",
    forLabel: "for Government",
    banner: "government",
    headline: "Govern every executive order, regulation and gazette as an Official Record.",
    intro:
      "A government's authority rests on documents that must be provably genuine years after they are issued. Sovereign Dispatch turns each policy, order and notice into a governed, certified, permanently verifiable Official Record — issued under the authority of an office, not an individual.",
    publications: ["Executive Orders", "Regulations & Statutory Instruments", "Official Gazettes", "Policy Directives", "Public Notices", "Ministerial Decisions"],
    authorities: ["Minister", "Permanent Secretary", "Director General", "Legal Counsel", "Government Gazette Office"],
    problems: [
      { t: "Authority that must outlive the official", d: "An order signed today must remain valid when the minister has moved on. Dispatch binds publication to the office, so authority is durable and never tied to a person who can leave." },
      { t: "Gazettes that anyone must be able to trust", d: "A circulating PDF of a regulation cannot prove it is the genuine, current version. Every Dispatch publication carries a permanent Record ID anyone can verify — with no account." },
      { t: "Provenance for every decision", d: "When a policy is challenged, the government must show who approved it, in what order, on what version. The evidence chain is recorded as the record is made, not reconstructed under pressure." },
    ],
    frameworks: ["ISO 27001-aligned controls", "National data-residency requirements", "Public-records retention law", "GDPR-aligned data handling"],
    metaTitle: "Sovereign Dispatch for Government — Govern Executive Orders, Regulations & Gazettes",
    metaDescription: "Turn executive orders, regulations and official gazettes into governed, certified, permanently verifiable Official Records — issued under the authority of an office. Institutional publication infrastructure for government.",
  },
  {
    slug: "healthcare",
    name: "Healthcare",
    forLabel: "for Healthcare",
    banner: "healthcare",
    headline: "Issue clinical directives and safety bulletins with governed, provable authority.",
    intro:
      "When a clinical directive or safety bulletin goes out, lives depend on it being the correct, current, authorised version. Sovereign Dispatch governs every health-authority publication through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Clinical Directives", "Patient-Safety Bulletins", "Treatment Protocols", "Health Authority Notices", "Infection-Control Guidance", "Recall & Alert Notices"],
    authorities: ["Hospital Director", "Chief Medical Officer", "Clinical Governance Officer", "Health Authority", "Quality & Safety Office"],
    problems: [
      { t: "The wrong protocol can never circulate", d: "A superseded treatment protocol must not be mistaken for the current one. Dispatch maintains a single authoritative record; revoked and outdated versions cannot pass as official." },
      { t: "Every directive is attributable", d: "Clinical governance demands proof of who authorised a directive and when. Approval is bound to a named office and the exact version, on the record." },
      { t: "Evidence ready for any inspection", d: "When a regulator or coroner asks how a safety bulletin was issued, the complete evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Clinical-governance frameworks", "Patient-data residency", "Health-records retention"],
    metaTitle: "Sovereign Dispatch for Healthcare — Govern Clinical Directives & Safety Bulletins",
    metaDescription: "Govern clinical directives, patient-safety bulletins and treatment protocols as certified, permanently verifiable Official Records. Attributable approval and a complete evidence chain for health authorities.",
  },
  {
    slug: "universities",
    name: "Universities",
    forLabel: "for Universities",
    banner: "universities",
    headline: "Govern senate decisions, degree regulations and academic policy as Official Records.",
    intro:
      "A university's resolutions, regulations and conferrals are institutional acts that must stand for decades. Sovereign Dispatch governs every senate decision and academic policy through its approval chain and preserves it as a verifiable Official Record.",
    publications: ["Senate & Council Decisions", "Degree Regulations", "Academic Policies", "Examination Regulations", "Research Governance Notices", "Conferral Records"],
    authorities: ["Vice Chancellor", "Registrar", "Academic Secretary", "Senate", "Council Secretariat"],
    problems: [
      { t: "Resolutions that survive every administration", d: "A senate resolution must remain authoritative long after the senate that passed it has changed. Authority belongs to the office and the record, not the sitting members." },
      { t: "Regulations students and employers can trust", d: "Degree and examination regulations are relied upon externally. A verifiable Record ID lets any party confirm the genuine, current version." },
      { t: "Provenance for accreditation and appeal", d: "When an accreditation body or an appeal questions a policy, the approval chain and evidence are already sealed to the record." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Academic-governance frameworks", "Student-data protection", "Research-records retention"],
    metaTitle: "Sovereign Dispatch for Universities — Govern Senate Decisions & Academic Policy",
    metaDescription: "Govern senate decisions, degree regulations and academic policies as certified, permanently verifiable Official Records. Durable institutional authority for universities, registrars and academic secretariats.",
  },
  {
    slug: "justice",
    name: "Justice",
    forLabel: "for Justice & the Courts",
    banner: "justice",
    headline: "Publish judgments, court rules and legal notices with permanent, provable integrity.",
    intro:
      "Judicial authority depends on the certainty that a published judgment or rule is genuine and unaltered. Sovereign Dispatch governs every court publication and seals it with a cryptographic integrity proof anyone can verify.",
    publications: ["Judgments & Rulings", "Court Rules & Practice Directions", "Legal Notices", "Cause Lists", "Sentencing Guidelines", "Registry Notices"],
    authorities: ["Judge", "Court Administrator", "Registrar", "Clerk of Court", "Judicial Council"],
    problems: [
      { t: "A judgment that cannot be altered", d: "An altered or forged judgment undermines the rule of law. Every Dispatch publication carries a SHA-256 integrity proof; a single byte changed will not match." },
      { t: "The authoritative version, always", d: "Practitioners and the public must reach the one official judgment, not a circulating copy. The permanent Record ID resolves to the authoritative record." },
      { t: "An unbroken evidence trail", d: "From issuance to preservation, every act is recorded in an append-only chain — the provenance a court of record requires." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Court-records retention", "Open-justice publication duties", "Data-residency requirements"],
    metaTitle: "Sovereign Dispatch for Justice — Govern Judgments, Court Rules & Legal Notices",
    metaDescription: "Publish judgments, court rules and legal notices as permanently verifiable Official Records with cryptographic integrity proofs. Tamper-evident judicial publication for courts and registries.",
  },
  {
    slug: "regulators",
    name: "Regulators",
    forLabel: "for Regulators",
    banner: "regulators",
    headline: "Issue licences, enforcement decisions and public notices with enforceable authority.",
    intro:
      "A regulator's decisions carry legal weight only if they can be proven genuine, current and properly authorised. Sovereign Dispatch governs every licence, enforcement action and notice as a certified, independently verifiable Official Record.",
    publications: ["Licences & Authorisations", "Enforcement Decisions", "Public Notices", "Regulatory Determinations", "Compliance Directives", "Sanction Notices"],
    authorities: ["Regulatory Commissioner", "Director of Enforcement", "Compliance Officer", "Licensing Authority", "Board Secretariat"],
    problems: [
      { t: "Decisions that hold up under challenge", d: "Enforcement is routinely contested. The governance certificate proves the decision satisfied its approval policy, office by office, in order." },
      { t: "Licences anyone can verify", d: "A licensed party — or the public — must be able to confirm a licence is genuine and unrevoked. Verification is public, by Record ID, with no account." },
      { t: "Revocation that is provable", d: "When an authorisation is withdrawn, verification shows it plainly — a circulating copy can never appear current." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Administrative-law evidentiary standards", "Public-register duties", "Records retention"],
    metaTitle: "Sovereign Dispatch for Regulators — Govern Licences, Enforcement & Public Notices",
    metaDescription: "Issue licences, enforcement decisions and public notices as certified, independently verifiable Official Records. Provable authorisation, public verification and provable revocation for regulators.",
  },
  {
    slug: "financial-institutions",
    name: "Financial Institutions",
    forLabel: "for Banks & Financial Institutions",
    banner: "financial-institutions",
    headline: "Govern board resolutions, policies and regulatory filings as Official Records.",
    intro:
      "Banks operate under constant scrutiny, where a board resolution or policy must be provably the version that was approved. Sovereign Dispatch governs every institutional decision through an enforced approval chain and seals it for audit and examination.",
    publications: ["Board & Committee Resolutions", "Risk & Compliance Policies", "Regulatory Filings", "Customer Notices", "Capital & Credit Decisions", "Governance Records"],
    authorities: ["Board Chair", "Corporate Secretary", "Chief Compliance Officer", "Chief Risk Officer", "Internal Audit"],
    problems: [
      { t: "Examination-ready evidence, always", d: "When a supervisor examines a decision, the governance certificate and evidence chain already prove who approved it, on what version, in order." },
      { t: "Separation of duties enforced", d: "Approval and publication are reserved to distinct authorities; an approver can never be the publisher — enforced and logged, not assumed." },
      { t: "Policy versions that cannot drift", d: "Only one authoritative version of a policy exists; superseded versions cannot be mistaken for current in a dispute or audit." },
    ],
    frameworks: ["SOC 2-aligned principles", "ISO 27001-aligned controls", "Basel / prudential governance", "Records retention & data residency"],
    metaTitle: "Sovereign Dispatch for Financial Institutions — Govern Board Resolutions & Filings",
    metaDescription: "Govern board resolutions, risk and compliance policies and regulatory filings as certified, examination-ready Official Records. Enforced separation of duties and a complete evidence chain for banks.",
  },
  {
    slug: "insurance",
    name: "Insurance",
    forLabel: "for Insurance",
    banner: "insurance",
    headline: "Govern policy wordings, regulatory notices and board decisions with provable authority.",
    intro:
      "Insurance rests on the precise, authoritative version of a policy or determination. Sovereign Dispatch governs every wording, notice and decision and seals it as a verifiable Official Record — so the version relied upon is provably the version that was approved.",
    publications: ["Policy Wordings & Endorsements", "Underwriting Guidelines", "Regulatory Notices", "Board & Committee Decisions", "Claims-Governance Directives", "Solvency Filings"],
    authorities: ["Chief Underwriting Officer", "Corporate Secretary", "Chief Compliance Officer", "Appointed Actuary", "Board Risk Committee"],
    problems: [
      { t: "The wording in force is provable", d: "Disputes turn on which version of a wording applied. The permanent Record ID and integrity proof settle which document was authoritative and when." },
      { t: "Decisions ready for the regulator", d: "Conduct and prudential supervisors expect provable governance. The evidence chain is produced as the decision is made." },
      { t: "Attributable, durable authority", d: "Authority belongs to the office, surviving the people who held it — essential for long-tail liabilities." },
    ],
    frameworks: ["SOC 2-aligned principles", "ISO 27001-aligned controls", "Conduct & prudential frameworks", "Records retention"],
    metaTitle: "Sovereign Dispatch for Insurance — Govern Policy Wordings & Regulatory Notices",
    metaDescription: "Govern policy wordings, underwriting guidelines and regulatory notices as certified, permanently verifiable Official Records. Provable version control and governance evidence for insurers.",
  },
  {
    slug: "energy-utilities",
    name: "Energy & Utilities",
    forLabel: "for Energy & Utilities",
    banner: "energy-utilities",
    headline: "Govern safety directives, tariff decisions and regulatory filings as Official Records.",
    intro:
      "Energy and utility operators issue safety-critical directives and regulated decisions that must be provably authorised. Sovereign Dispatch governs each one through its approval chain and preserves it as a verifiable, tamper-evident Official Record.",
    publications: ["Safety Directives & Bulletins", "Tariff & Pricing Decisions", "Regulatory Filings", "Operational Standards", "Outage & Incident Notices", "Board Resolutions"],
    authorities: ["Chief Operating Officer", "Safety Director", "Regulatory Affairs", "Corporate Secretary", "Board Safety Committee"],
    problems: [
      { t: "Safety directives that are never in doubt", d: "A safety directive must be unambiguously the current, authorised version. One authoritative record; integrity proof against tampering." },
      { t: "Regulated decisions, provably governed", d: "Tariff and licensing decisions are scrutinised. The governance certificate proves the approval policy was satisfied." },
      { t: "Provenance across decades", d: "Infrastructure outlives staff; the record's authority and evidence outlive them too." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Sector safety regulation", "Regulatory-filing standards", "Records retention"],
    metaTitle: "Sovereign Dispatch for Energy & Utilities — Govern Safety Directives & Tariff Decisions",
    metaDescription: "Govern safety directives, tariff decisions and regulatory filings as certified, tamper-evident Official Records. Provable authorisation and durable provenance for energy and utility operators.",
  },
  {
    slug: "defence",
    name: "Defence",
    forLabel: "for Defence",
    banner: "defence",
    headline: "Govern directives, doctrine and orders with sovereign control and provable authority.",
    intro:
      "Defence institutions issue directives and doctrine where authenticity, classification and sovereignty are non-negotiable. Sovereign Dispatch governs each publication under classification and clearance controls and preserves it within sovereign boundaries.",
    publications: ["Directives & Orders", "Doctrine & Standing Instructions", "Policy Determinations", "Classified Notices", "Procurement Authorisations", "Board & Council Decisions"],
    authorities: ["Permanent Secretary", "Chief of Staff", "Directorate Heads", "Security Authority", "Records & Archives"],
    problems: [
      { t: "Classification enforced at the core", d: "Documents carry classification; reads and approvals are gated against clearance — isolation by default, not bolted on." },
      { t: "Sovereign by deployment", d: "Records can be held within approved national boundaries, on-premise or air-gapped — sovereignty is a deployment decision." },
      { t: "Authority that cannot be forged", d: "Orders are issued under an office with a provable approval chain; a forged or altered copy cannot verify." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Classification & clearance handling", "Sovereign / air-gapped deployment", "Defence records retention"],
    metaTitle: "Sovereign Dispatch for Defence — Govern Directives, Doctrine & Orders",
    metaDescription: "Govern defence directives, doctrine and orders under classification and clearance controls, preserved within sovereign boundaries. Tamper-evident authority for defence institutions.",
  },
  {
    slug: "municipalities",
    name: "Municipalities",
    forLabel: "for Municipalities & Local Government",
    banner: "municipalities",
    headline: "Govern by-laws, council resolutions and public notices as verifiable Official Records.",
    intro:
      "Local government issues by-laws, resolutions and notices that residents and courts must be able to trust. Sovereign Dispatch governs each one through its approval chain and makes it permanently verifiable by anyone.",
    publications: ["By-laws & Ordinances", "Council Resolutions", "Public Notices", "Planning & Permit Decisions", "Tender Awards", "Local Gazettes"],
    authorities: ["Mayor", "Town Clerk", "Municipal Manager", "Council Secretariat", "Legal Services"],
    problems: [
      { t: "By-laws residents can verify", d: "A by-law or notice must be confirmable as genuine and current. The permanent Record ID makes public verification trivial." },
      { t: "Decisions provably governed", d: "Planning and tender decisions are frequently challenged; the governance certificate proves due process." },
      { t: "Continuity across council terms", d: "Authority belongs to the office and survives every election and staff change." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Local-government records law", "Open-data / transparency duties", "Retention schedules"],
    metaTitle: "Sovereign Dispatch for Municipalities — Govern By-laws, Resolutions & Notices",
    metaDescription: "Govern by-laws, council resolutions and public notices as certified, publicly verifiable Official Records. Provable due process and durable authority for municipalities and local government.",
  },
  {
    slug: "ngos",
    name: "NGOs",
    forLabel: "for NGOs & Non-Profits",
    banner: "ngos",
    headline: "Govern board resolutions, grant decisions and policies with donor-grade provenance.",
    intro:
      "NGOs answer to donors, regulators and the public, where governance and provenance build trust. Sovereign Dispatch governs every board decision, grant approval and policy as a certified, verifiable Official Record.",
    publications: ["Board & Trustee Resolutions", "Grant & Funding Decisions", "Governance Policies", "Donor & Compliance Reports", "Safeguarding Directives", "Public Statements"],
    authorities: ["Board Chair", "Executive Director", "Company Secretary", "Compliance Officer", "Audit Committee"],
    problems: [
      { t: "Donor and regulator trust, earned", d: "Funders demand evidence of governance. The evidence chain proves how each decision was made, ready for any review." },
      { t: "Grant decisions provably attributable", d: "Who approved a grant, on what basis, is recorded and bound to the office — protecting the organisation in disputes." },
      { t: "Institutional memory preserved", d: "Provenance and authority survive volunteer and staff turnover, common in the sector." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Charity-governance codes", "Donor-reporting standards", "Data protection"],
    metaTitle: "Sovereign Dispatch for NGOs — Govern Board Resolutions & Grant Decisions",
    metaDescription: "Govern board resolutions, grant decisions and governance policies as certified, verifiable Official Records with donor-grade provenance. Institutional trust for NGOs and non-profits.",
  },
  {
    slug: "religious-institutions",
    name: "Religious Institutions",
    forLabel: "for Churches & Religious Institutions",
    banner: "religious-institutions",
    headline: "Govern doctrinal decisions, canonical records and official statements as Official Records.",
    intro:
      "Religious institutions hold records and decisions that must endure for generations and remain provably authentic. Sovereign Dispatch governs each canonical decision and official statement and preserves it as a permanent, verifiable Official Record.",
    publications: ["Doctrinal & Synod Decisions", "Canonical Records", "Official Statements & Pastoral Letters", "Appointments & Ordinations", "Governance Resolutions", "Property & Trust Records"],
    authorities: ["Presiding Authority", "Synod / Council", "General Secretary", "Registrar", "Trustees"],
    problems: [
      { t: "Records that must endure for generations", d: "Canonical and governance records are kept for the very long term; preservation is sealed and tamper-evident." },
      { t: "Decisions of provable authority", d: "Synod and council decisions carry weight only if genuine; the approval chain and Record ID make them verifiable." },
      { t: "Continuity beyond any leadership", d: "Authority belongs to the office and the institution, surviving every change of leadership." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Long-term preservation", "Trust & property governance", "Data protection"],
    metaTitle: "Sovereign Dispatch for Religious Institutions — Govern Doctrinal & Canonical Records",
    metaDescription: "Govern doctrinal decisions, canonical records and official statements as permanently verifiable Official Records. Generational preservation and provable authority for religious institutions.",
  },
  {
    slug: "museums",
    name: "Museums",
    forLabel: "for Museums & Cultural Institutions",
    banner: "museums",
    headline: "Govern acquisition, provenance and deaccession decisions as Official Records.",
    intro:
      "Museums live and die by provenance. Sovereign Dispatch governs every acquisition, loan and deaccession decision through an approval chain and seals it as a permanent, verifiable record of institutional authority.",
    publications: ["Acquisition Decisions", "Provenance Records", "Deaccession Resolutions", "Loan Agreements & Authorisations", "Conservation Directives", "Board Resolutions"],
    authorities: ["Director", "Chief Curator", "Registrar", "Acquisitions Committee", "Board of Trustees"],
    problems: [
      { t: "Provenance that is itself provable", d: "A museum's provenance records must be trustworthy. Each decision is sealed with an integrity proof and an evidence chain." },
      { t: "Deaccession that withstands scrutiny", d: "Deaccession is contentious; the governance certificate proves the decision satisfied its policy and authority." },
      { t: "Authority across centuries", d: "Records outlive directors and trustees; their authority and provenance outlive them too." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Collections-governance codes", "Provenance & ethics standards", "Long-term preservation"],
    metaTitle: "Sovereign Dispatch for Museums — Govern Acquisition, Provenance & Deaccession",
    metaDescription: "Govern acquisition, provenance and deaccession decisions as certified, permanently verifiable Official Records. Trustworthy provenance and durable authority for museums and cultural institutions.",
  },
  {
    slug: "archives",
    name: "National Archives",
    forLabel: "for Archives & Records Authorities",
    banner: "archives",
    headline: "Preserve the nation's records with tamper-evident, permanently verifiable integrity.",
    intro:
      "An archive's mandate is to keep records that can be proven authentic indefinitely. Sovereign Dispatch seals every record with a preservation certificate and a SHA-256 integrity proof, and makes it independently verifiable for its full retention life.",
    publications: ["Preservation Certificates", "Accession Records", "Retention & Disposal Schedules", "Authenticity Determinations", "Access Decisions", "Transfer Records"],
    authorities: ["National Archivist", "Head of Preservation", "Records Authority", "Accessions Office", "Access & Disclosure"],
    problems: [
      { t: "Authenticity provable for decades", d: "A preserved record must be provably unaltered years later. Every record carries a tamper-evident integrity proof anyone can check." },
      { t: "Terminal, immutable preservation", d: "Once archived, a record's state is terminal — no edit, withdrawal or republication is possible." },
      { t: "Verification without an account", d: "Any citizen or researcher can confirm a record is genuine by its permanent identifier." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Archival preservation standards", "Public-records law", "Data residency"],
    metaTitle: "Sovereign Dispatch for Archives — Tamper-Evident Preservation of the Public Record",
    metaDescription: "Preserve records with tamper-evident, permanently verifiable integrity proofs and terminal, immutable preservation. Authenticity that holds for decades for national archives and records authorities.",
  },
  {
    slug: "pharmaceuticals",
    name: "Pharmaceuticals",
    forLabel: "for Pharmaceuticals",
    banner: "pharmaceuticals",
    headline: "Govern regulatory submissions, SOPs and safety notices with audit-ready provenance.",
    intro:
      "Pharmaceutical governance is unforgiving: the version of an SOP, submission or safety notice that was approved must be provable. Sovereign Dispatch governs each one through an enforced approval chain and seals it for inspection.",
    publications: ["Standard Operating Procedures", "Regulatory Submissions", "Safety & Recall Notices", "Quality Directives", "Batch-Release Decisions", "Board & Committee Resolutions"],
    authorities: ["Qualified Person", "Head of Quality", "Regulatory Affairs", "Pharmacovigilance Officer", "Site Director"],
    problems: [
      { t: "The approved version is provable", d: "GxP turns on document control. The permanent Record ID and integrity proof establish exactly which version was authorised." },
      { t: "Inspection-ready at all times", d: "When an inspector asks how an SOP or release was approved, the evidence chain already exists, attributable and ordered." },
      { t: "Separation of duties enforced", d: "Approval and release authorities are distinct and logged — assumption is never enough in a regulated environment." },
    ],
    frameworks: ["GxP / GMP document control", "ISO 27001-aligned controls", "Pharmacovigilance standards", "Records retention"],
    metaTitle: "Sovereign Dispatch for Pharmaceuticals — Govern SOPs, Submissions & Safety Notices",
    metaDescription: "Govern SOPs, regulatory submissions and safety notices as certified, inspection-ready Official Records. Provable version control, enforced separation of duties and a complete evidence chain.",
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    forLabel: "for Manufacturing",
    banner: "manufacturing",
    headline: "Govern quality standards, safety directives and board decisions as Official Records.",
    intro:
      "Manufacturers depend on the precise, authorised version of a standard or directive reaching the floor. Sovereign Dispatch governs every quality standard, safety directive and decision and seals it as a verifiable Official Record.",
    publications: ["Quality Standards & Specifications", "Safety Directives", "Engineering Change Decisions", "Supplier & Compliance Policies", "Recall Notices", "Board Resolutions"],
    authorities: ["Quality Director", "Head of Operations", "Engineering Authority", "Compliance Officer", "Board"],
    problems: [
      { t: "One authoritative specification", d: "A superseded spec on the floor causes defects and recalls. Dispatch keeps a single authoritative version; outdated copies cannot pass as current." },
      { t: "Change decisions provably governed", d: "Engineering and quality changes are auditable; the governance certificate proves who approved them, in order." },
      { t: "Evidence for certification and recall", d: "When a certifier or a recall demands proof, the evidence chain is already there." },
    ],
    frameworks: ["ISO 9001 / quality-management alignment", "ISO 27001-aligned controls", "Product-safety regulation", "Records retention"],
    metaTitle: "Sovereign Dispatch for Manufacturing — Govern Quality Standards & Safety Directives",
    metaDescription: "Govern quality standards, safety directives and engineering-change decisions as certified, verifiable Official Records. One authoritative specification and audit-ready evidence for manufacturers.",
  },
  {
    slug: "central-banks",
    name: "Central Banks",
    forLabel: "for Central Banks",
    banner: "central-banks",
    headline: "Issue monetary policy, circulars and prudential rules as Official Records.",
    intro:
      "A central bank's word moves markets — so a circular or rate decision must be provably the genuine, current instrument the moment it is read. Sovereign Dispatch governs every monetary and prudential publication through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Monetary Policy Decisions", "Prudential Regulations & Circulars", "Supervisory Directives", "Exchange-Control Notices", "Financial-Stability Statements", "Licensing Decisions"],
    authorities: ["Governor", "Deputy Governor", "Monetary Policy Committee", "Head of Supervision", "Legal Counsel"],
    problems: [
      { t: "Market-moving text that must be unforgeable", d: "A fabricated or altered circular can move a currency. Every Dispatch publication carries a permanent Record ID that any bank, market or citizen can verify — with no account." },
      { t: "Authority bound to the mandate, not the person", d: "A supervisory directive must hold when the Governor changes. Dispatch binds issuance to the office, so the mandate's authority is durable." },
      { t: "Provenance for every supervisory action", d: "When a prudential decision is contested, the bank must show who approved it, on what version, in what order. The evidence chain exists as the record is made." },
    ],
    frameworks: ["Basel-aligned supervisory practice", "ISO 27001-aligned controls", "National monetary law", "Financial-records retention"],
    metaTitle: "Sovereign Dispatch for Central Banks — Govern Monetary Policy & Prudential Circulars",
    metaDescription: "Govern monetary policy decisions, prudential regulations and supervisory directives as certified, permanently verifiable Official Records. Unforgeable issuance and a complete evidence chain for central banks.",
  },
  {
    slug: "tax-authorities",
    name: "Tax Authorities",
    forLabel: "for Tax Authorities",
    banner: "tax-authorities",
    headline: "Govern tax rulings, public notices and assessments as Official Records.",
    intro:
      "A tax authority's rulings and notices carry the force of law and are relied on for years. Sovereign Dispatch governs every ruling, determination and public notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Tax Rulings & Determinations", "Public Notices & Circulars", "Assessment Notices", "Practice Directions", "Tariff & Rate Schedules", "Compliance Guidance"],
    authorities: ["Commissioner", "Director of Rulings", "Legal Counsel", "Head of Compliance", "Appeals Office"],
    problems: [
      { t: "Rulings taxpayers can rely on", d: "A taxpayer must prove which ruling was in force when they acted. Dispatch maintains a single authoritative record with a permanent Record ID; superseded versions cannot pass as current." },
      { t: "Determinations that are attributable", d: "When a ruling is appealed, the authority must show who issued it under what delegation. Approval is bound to a named office and the exact version, on the record." },
      { t: "Audit-ready by default", d: "When an inspector or tribunal asks how a determination was made, the evidence chain already exists — produced as the record was made, not reconstructed." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Taxpayer-data residency", "Public-records retention law", "Administrative-law disclosure"],
    metaTitle: "Sovereign Dispatch for Tax Authorities — Govern Rulings, Notices & Assessments",
    metaDescription: "Govern tax rulings, public notices and assessments as certified, permanently verifiable Official Records. Reliable rulings, attributable determinations and audit-ready evidence for revenue authorities.",
  },
  {
    slug: "electoral-commissions",
    name: "Electoral Commissions",
    forLabel: "for Electoral Commissions",
    banner: "electoral-commissions",
    headline: "Certify results, rolls and electoral notices as permanently verifiable Official Records.",
    intro:
      "Public trust in an election rests on every result and notice being provably genuine and unaltered. Sovereign Dispatch governs each declaration, electoral-roll publication and notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Result Declarations", "Electoral Rolls & Registers", "Candidate & Nomination Notices", "Boundary Determinations", "Regulatory Guidance", "Returning-Officer Decisions"],
    authorities: ["Chief Electoral Officer", "Returning Officers", "Commission Board", "Legal Counsel", "Results Office"],
    problems: [
      { t: "Results no one can dispute the provenance of", d: "A circulating tally cannot prove it is the genuine declaration. Every Dispatch result carries a permanent Record ID anyone can verify independently — with no account." },
      { t: "Authority bound to the office", d: "A declaration must hold beyond the official who signed it. Dispatch binds publication to the returning office, so authority survives any handover." },
      { t: "Evidence for every challenge", d: "When a result is contested, the commission must show who certified it, on what version, in what order. The evidence chain is recorded as the declaration is made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Election-integrity practice", "National data-residency requirements", "Public-records retention law"],
    metaTitle: "Sovereign Dispatch for Electoral Commissions — Certify Results & Electoral Rolls",
    metaDescription: "Certify result declarations, electoral rolls and notices as permanently verifiable Official Records. Independent verification, durable authority and a complete evidence chain for electoral commissions.",
  },
  {
    slug: "parliaments",
    name: "Parliaments & Legislatures",
    forLabel: "for Parliaments",
    banner: "parliaments",
    headline: "Govern bills, acts, resolutions and the official record as Official Records.",
    intro:
      "A legislature's authority depends on the exact, authentic text of what it enacted. Sovereign Dispatch governs every bill, act, resolution and proceeding through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Bills & Enacted Acts", "Resolutions & Motions", "Official Report (Hansard)", "Committee Reports", "Standing Orders", "Procedural Rulings"],
    authorities: ["Speaker", "Clerk of the House", "Parliamentary Counsel", "Committee Chairs", "Records Office"],
    problems: [
      { t: "The authentic text, provably", d: "Courts and citizens must rely on the exact enacted version. Dispatch maintains a single authoritative record with a permanent Record ID; drafts and superseded versions cannot pass as law." },
      { t: "Authority bound to the House", d: "The record must hold across sessions and Speakers. Dispatch binds publication to the office of the House, so authority is durable." },
      { t: "Provenance of every proceeding", d: "When an enactment is litigated, the legislature must show the version and the chain of approval. The evidence chain exists as the record is made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Public-records retention law", "National data-residency requirements", "Open-records disclosure"],
    metaTitle: "Sovereign Dispatch for Parliaments — Govern Bills, Acts & the Official Report",
    metaDescription: "Govern bills, enacted acts, resolutions and the official report as certified, permanently verifiable Official Records. The authentic text, durable authority and complete provenance for legislatures.",
  },
  {
    slug: "law-enforcement",
    name: "Law Enforcement",
    forLabel: "for Law Enforcement",
    banner: "law-enforcement",
    headline: "Issue standing orders, public-safety notices and directives as Official Records.",
    intro:
      "A police service runs on orders and notices that must be provably authentic and current in the field and in court. Sovereign Dispatch governs every standing order, directive and public-safety notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Standing Orders", "Operational Directives", "Public-Safety Notices", "Policy & Conduct Instructions", "Wanted & Alert Notices", "Command Decisions"],
    authorities: ["Chief Constable / Commissioner", "Deputy Commissioner", "Head of Professional Standards", "Legal Counsel", "Command Office"],
    problems: [
      { t: "The current order can never be in doubt", d: "A superseded standing order must not govern an officer's action. Dispatch keeps one authoritative version; revoked orders cannot pass as current." },
      { t: "Every directive attributable in court", d: "When conduct is reviewed, the service must show who authorised an order under what command. Approval is bound to a named office and the exact version." },
      { t: "Evidence ready for oversight", d: "When an oversight body or court asks how a directive was issued, the evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Evidence-handling standards", "National data-residency requirements", "Public-records retention law"],
    metaTitle: "Sovereign Dispatch for Law Enforcement — Govern Standing Orders & Directives",
    metaDescription: "Govern standing orders, operational directives and public-safety notices as certified, permanently verifiable Official Records. One current order, attributable command and oversight-ready evidence.",
  },
  {
    slug: "customs-border",
    name: "Customs & Border",
    forLabel: "for Customs & Border Authorities",
    banner: "customs-border",
    headline: "Govern tariffs, customs notices and import rules as Official Records.",
    intro:
      "Trade depends on tariff schedules and customs notices being the precise, authorised version at the border. Sovereign Dispatch governs every tariff, rule and notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Tariff Schedules", "Customs Notices & Circulars", "Import & Export Rules", "Valuation & Classification Rulings", "Prohibition & Restriction Lists", "Border Directives"],
    authorities: ["Director General of Customs", "Head of Tariff Policy", "Legal Counsel", "Head of Compliance", "Rulings Office"],
    problems: [
      { t: "One authoritative tariff", d: "An out-of-date schedule at the border means wrong duties and disputes. Dispatch keeps a single authoritative version with a permanent Record ID; superseded schedules cannot pass as current." },
      { t: "Rulings traders can rely on", d: "A classification ruling must be provably the one in force. Approval is bound to a named office and the exact version, on the record." },
      { t: "Evidence for every dispute", d: "When a duty assessment is challenged, the evidence chain of who decided what, on which version, already exists." },
    ],
    frameworks: ["WCO-aligned customs practice", "ISO 27001-aligned controls", "Trade-data residency", "Public-records retention law"],
    metaTitle: "Sovereign Dispatch for Customs & Border — Govern Tariffs & Customs Notices",
    metaDescription: "Govern tariff schedules, customs notices and classification rulings as certified, permanently verifiable Official Records. One authoritative tariff and dispute-ready evidence for customs authorities.",
  },
  {
    slug: "aviation-authorities",
    name: "Aviation Authorities",
    forLabel: "for Civil Aviation Authorities",
    banner: "aviation-authorities",
    headline: "Govern airworthiness directives, regulations and notices as Official Records.",
    intro:
      "In aviation, the wrong version of a directive endangers lives. Sovereign Dispatch governs every airworthiness directive, regulation and aeronautical notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Airworthiness Directives", "Civil Aviation Regulations", "Aeronautical Notices", "Operator & Licensing Decisions", "Safety Bulletins", "Certification Determinations"],
    authorities: ["Director of Civil Aviation", "Head of Airworthiness", "Flight Standards Office", "Legal Counsel", "Certification Authority"],
    problems: [
      { t: "Only the current directive may fly", d: "A superseded airworthiness directive must never be acted on. Dispatch maintains one authoritative version; revoked directives cannot pass as official." },
      { t: "Certification provably governed", d: "When a certificate is questioned, the authority must show who approved it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every investigation", d: "When a safety investigation asks how a directive was issued, the complete evidence chain already exists." },
    ],
    frameworks: ["ICAO-aligned standards", "ISO 27001-aligned controls", "Safety-management systems", "Aviation-records retention"],
    metaTitle: "Sovereign Dispatch for Aviation Authorities — Govern Airworthiness Directives",
    metaDescription: "Govern airworthiness directives, civil aviation regulations and aeronautical notices as certified, permanently verifiable Official Records. One current directive and investigation-ready evidence.",
  },
  {
    slug: "maritime-authorities",
    name: "Maritime Authorities",
    forLabel: "for Maritime Authorities",
    banner: "maritime-authorities",
    headline: "Govern marine notices, port regulations and directives as Official Records.",
    intro:
      "Safe shipping depends on marine notices and port regulations being the authentic, current version. Sovereign Dispatch governs every marine notice, regulation and directive through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Marine Notices", "Port & Harbour Regulations", "Notices to Mariners", "Vessel & Flag Decisions", "Safety Directives", "Survey & Certification Determinations"],
    authorities: ["Director of Maritime Affairs", "Harbour Master", "Flag-State Authority", "Legal Counsel", "Survey Office"],
    problems: [
      { t: "One authoritative marine notice", d: "An outdated notice to mariners risks lives and cargo. Dispatch keeps a single authoritative version with a permanent Record ID; superseded notices cannot pass as current." },
      { t: "Flag-state decisions attributable", d: "When a certificate or detention is contested, the authority must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every casualty inquiry", d: "When an inquiry asks how a directive was issued, the evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["IMO-aligned conventions", "ISO 27001-aligned controls", "Flag-state administration practice", "Maritime-records retention"],
    metaTitle: "Sovereign Dispatch for Maritime Authorities — Govern Marine Notices & Port Rules",
    metaDescription: "Govern marine notices, port regulations and flag-state decisions as certified, permanently verifiable Official Records. One authoritative notice and inquiry-ready evidence for maritime authorities.",
  },
  {
    slug: "environmental-agencies",
    name: "Environmental Agencies",
    forLabel: "for Environmental Agencies",
    banner: "environmental-agencies",
    headline: "Govern permits, environmental notices and standards as Official Records.",
    intro:
      "Environmental permits and notices are relied on — and litigated — for decades. Sovereign Dispatch governs every permit, determination and standard through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Environmental Permits", "Enforcement Notices", "Emission & Discharge Standards", "Impact-Assessment Determinations", "Public Consultation Notices", "Remediation Orders"],
    authorities: ["Director of Environmental Protection", "Head of Permitting", "Enforcement Office", "Legal Counsel", "Technical Assessment Board"],
    problems: [
      { t: "Permits that hold up for decades", d: "A permit issued today must be provable in a challenge years later. Dispatch maintains a single authoritative record with a permanent Record ID; superseded conditions cannot pass as current." },
      { t: "Enforcement that is attributable", d: "When an enforcement notice is appealed, the agency must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every legal challenge", d: "When a determination is litigated, the complete evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 14001-aligned practice", "ISO 27001-aligned controls", "Environmental-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Environmental Agencies — Govern Permits & Enforcement Notices",
    metaDescription: "Govern environmental permits, enforcement notices and standards as certified, permanently verifiable Official Records. Durable permits, attributable enforcement and litigation-ready evidence.",
  },
  {
    slug: "intellectual-property",
    name: "Intellectual Property Offices",
    forLabel: "for Patent & Trademark Offices",
    banner: "intellectual-property",
    headline: "Govern grants, registrations and the official journal as Official Records.",
    intro:
      "A patent grant or trademark registration is a property right that must be provably authentic for its full term. Sovereign Dispatch governs every grant, registration and journal entry through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Patent Grants", "Trademark & Design Registrations", "Official IP Journal", "Examination Decisions", "Opposition & Revocation Rulings", "Renewal & Lapse Notices"],
    authorities: ["Registrar / Controller", "Head of Examination", "Hearing Officers", "Legal Counsel", "Journal Office"],
    problems: [
      { t: "Rights provable for their full term", d: "A registration certificate must be verifiable decades later. Every Dispatch grant carries a permanent Record ID anyone can verify — with no account." },
      { t: "Examination decisions attributable", d: "When a grant is opposed, the office must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every dispute", d: "When validity is litigated, the chain of examination and grant already exists as a record." },
    ],
    frameworks: ["WIPO-aligned practice", "ISO 27001-aligned controls", "IP-records retention", "Open-register disclosure"],
    metaTitle: "Sovereign Dispatch for IP Offices — Govern Patent Grants & Trademark Registrations",
    metaDescription: "Govern patent grants, trademark registrations and the official IP journal as certified, permanently verifiable Official Records. Rights provable for their full term, with a complete evidence chain.",
  },
  {
    slug: "national-statistics",
    name: "National Statistics Offices",
    forLabel: "for National Statistics Offices",
    banner: "national-statistics",
    headline: "Govern official statistics, census results and releases as Official Records.",
    intro:
      "Official statistics steer policy and markets, so each release must be provably the genuine, unrevised-or-clearly-revised figure. Sovereign Dispatch governs every statistical release, census result and methodology note through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Official Statistical Releases", "Census Results", "Methodology Notes", "Revisions & Corrections", "Classification Standards", "Embargoed Bulletins"],
    authorities: ["National Statistician", "Head of Methodology", "Release Authority", "Legal Counsel", "Statistics Board"],
    problems: [
      { t: "Figures provably genuine", d: "A circulating number cannot prove it is the official release. Every Dispatch release carries a permanent Record ID anyone can verify independently — with no account." },
      { t: "Revisions transparently governed", d: "A revision must be distinguishable from the original. Dispatch records each version and the office that authorised it, on the record." },
      { t: "Evidence for every methodology query", d: "When a release is questioned, the chain of approval and the exact version already exist as a record." },
    ],
    frameworks: ["UN Fundamental Principles of Official Statistics", "ISO 27001-aligned controls", "Statistical-confidentiality law", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for National Statistics — Govern Official Releases & Census",
    metaDescription: "Govern official statistical releases, census results and revisions as certified, permanently verifiable Official Records. Genuine figures, transparent revisions and a complete evidence chain.",
  },
  {
    slug: "land-registries",
    name: "Land Registries",
    forLabel: "for Land Registries",
    banner: "land-registries",
    headline: "Govern title records, cadastral notices and determinations as Official Records.",
    intro:
      "Property rights depend on a title record being provably authentic and current. Sovereign Dispatch governs every title entry, cadastral notice and registration determination through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Title Registrations", "Cadastral Notices", "Charge & Encumbrance Entries", "Boundary Determinations", "Registration Decisions", "Public Notices"],
    authorities: ["Chief Land Registrar", "District Registrars", "Legal Counsel", "Survey Authority", "Adjudication Office"],
    problems: [
      { t: "Titles provable for their lifetime", d: "A title document must be verifiable as the genuine, current entry. Every Dispatch registration carries a permanent Record ID anyone can verify — with no account." },
      { t: "Registration decisions attributable", d: "When ownership is disputed, the registry must show who registered what, on which version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every adjudication", d: "When a boundary or charge is litigated, the chain of registration already exists as a record." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Land-registration law", "National data-residency requirements", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Land Registries — Govern Title Records & Cadastral Notices",
    metaDescription: "Govern title registrations, cadastral notices and registration decisions as certified, permanently verifiable Official Records. Provable titles, attributable decisions and adjudication-ready evidence.",
  },
  {
    slug: "standards-bodies",
    name: "Standards Bodies",
    forLabel: "for Standards Bodies",
    banner: "standards-bodies",
    headline: "Govern published standards, specifications and amendments as Official Records.",
    intro:
      "Industry relies on a published standard being the precise, current, authorised text. Sovereign Dispatch governs every standard, specification and amendment through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Published Standards", "Technical Specifications", "Amendments & Corrigenda", "Conformity-Assessment Schemes", "Withdrawal Notices", "Committee Decisions"],
    authorities: ["Director of Standards", "Technical Committee Chairs", "Head of Publishing", "Legal Counsel", "Approvals Board"],
    problems: [
      { t: "One authoritative edition", d: "A superseded edition in use causes non-conformity. Dispatch keeps a single authoritative version with a permanent Record ID; withdrawn editions cannot pass as current." },
      { t: "Amendments provably governed", d: "Each corrigendum must be traceable to the committee that approved it. Approval is bound to a named office and the exact version, on the record." },
      { t: "Evidence for every conformity claim", d: "When a conformity claim is checked, the chain of approval and the exact edition already exist as a record." },
    ],
    frameworks: ["ISO/IEC directives alignment", "ISO 27001-aligned controls", "Standards-development practice", "Records retention"],
    metaTitle: "Sovereign Dispatch for Standards Bodies — Govern Published Standards & Amendments",
    metaDescription: "Govern published standards, technical specifications and amendments as certified, permanently verifiable Official Records. One authoritative edition and conformity-ready evidence for standards bodies.",
  },
  {
    slug: "professional-bodies",
    name: "Professional & Licensing Bodies",
    forLabel: "for Professional & Licensing Bodies",
    banner: "professional-bodies",
    headline: "Govern licences, standards and disciplinary rulings as Official Records.",
    intro:
      "A professional body's register, standards and rulings are relied on by the public and the courts. Sovereign Dispatch governs every licence, standard and disciplinary decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Licence & Registration Decisions", "Professional Standards & Codes", "Disciplinary Rulings", "Practice Directions", "Register Notices", "Continuing-Competence Requirements"],
    authorities: ["Registrar", "Council / Board", "Disciplinary Tribunal", "Legal Counsel", "Standards Committee"],
    problems: [
      { t: "A register the public can trust", d: "Anyone must be able to confirm a practitioner's standing. Every Dispatch register entry carries a permanent Record ID anyone can verify — with no account." },
      { t: "Disciplinary rulings attributable", d: "When a ruling is appealed, the body must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every appeal", d: "When a decision is challenged, the chain of approval already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Professional-regulation practice", "Natural-justice disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Professional Bodies — Govern Licences & Disciplinary Rulings",
    metaDescription: "Govern licence decisions, professional standards and disciplinary rulings as certified, permanently verifiable Official Records. A trustworthy register and appeal-ready evidence for licensing bodies.",
  },
  {
    slug: "foreign-affairs",
    name: "Foreign Affairs",
    forLabel: "for Ministries of Foreign Affairs",
    banner: "foreign-affairs",
    headline: "Govern diplomatic notes, treaties and communiqués as Official Records.",
    intro:
      "A diplomatic instrument must be provably authentic across governments and decades. Sovereign Dispatch governs every note, treaty text and communiqué through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Diplomatic Notes", "Treaty & Agreement Texts", "Official Communiqués", "Consular Notices", "Accreditation Decisions", "Policy Statements"],
    authorities: ["Foreign Minister", "Permanent Secretary", "Head of Mission", "Legal Adviser", "Protocol Office"],
    problems: [
      { t: "Authentic text across borders", d: "A treaty or note must be verifiable by another state. Every Dispatch instrument carries a permanent Record ID any party can verify independently — with no account." },
      { t: "Authority bound to the office", d: "A communiqué must hold when the minister changes. Dispatch binds issuance to the office, so authority is durable across postings." },
      { t: "Provenance for every instrument", d: "When an agreement is disputed, the ministry must show the exact text and chain of approval. The evidence chain exists as the record is made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Diplomatic-archives practice", "National data-residency requirements", "Public-records retention law"],
    metaTitle: "Sovereign Dispatch for Foreign Affairs — Govern Diplomatic Notes & Treaties",
    metaDescription: "Govern diplomatic notes, treaty texts and communiqués as certified, permanently verifiable Official Records. Authentic text across borders and a complete evidence chain for foreign ministries.",
  },
  {
    slug: "social-security",
    name: "Social Security",
    forLabel: "for Social-Security Agencies",
    banner: "social-security",
    headline: "Govern benefit determinations, pension notices and rulings as Official Records.",
    intro:
      "A benefit determination is relied on by a citizen and must be provably the genuine decision. Sovereign Dispatch governs every determination, pension notice and policy ruling through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Benefit Determinations", "Pension & Entitlement Notices", "Policy Rulings", "Contribution Statements", "Appeal Decisions", "Public Guidance"],
    authorities: ["Director General", "Head of Benefits", "Appeals Office", "Legal Counsel", "Policy Authority"],
    problems: [
      { t: "Determinations a citizen can rely on", d: "A claimant must prove the decision that was made. Dispatch maintains a single authoritative record with a permanent Record ID; superseded determinations cannot pass as current." },
      { t: "Decisions that are attributable", d: "When an entitlement is appealed, the agency must show who decided under what delegation. Approval is bound to a named office and the exact version." },
      { t: "Audit-ready by default", d: "When an auditor or tribunal asks how a determination was made, the evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Citizen-data residency", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Social Security — Govern Benefit Determinations & Pensions",
    metaDescription: "Govern benefit determinations, pension notices and appeal decisions as certified, permanently verifiable Official Records. Reliable, attributable decisions and audit-ready evidence for social-security agencies.",
  },
  {
    slug: "labor-authorities",
    name: "Labour Authorities",
    forLabel: "for Labour & Employment Authorities",
    banner: "labor-authorities",
    headline: "Govern wage orders, workplace directives and rulings as Official Records.",
    intro:
      "Wage orders and workplace directives carry legal force and are relied on by employers and workers alike. Sovereign Dispatch governs every order, directive and ruling through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Wage Orders", "Workplace-Safety Directives", "Employment Rulings", "Inspection Notices", "Collective-Agreement Registrations", "Policy Guidance"],
    authorities: ["Director of Labour", "Chief Inspector", "Adjudication Office", "Legal Counsel", "Policy Authority"],
    problems: [
      { t: "One authoritative wage order", d: "An outdated wage order causes underpayment and disputes. Dispatch keeps a single authoritative version with a permanent Record ID; superseded orders cannot pass as current." },
      { t: "Directives provably governed", d: "When a safety directive is challenged, the authority must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every dispute", d: "When an inspection or ruling is contested, the chain of approval already exists as a record." },
    ],
    frameworks: ["ILO-aligned labour practice", "ISO 27001-aligned controls", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Labour Authorities — Govern Wage Orders & Workplace Directives",
    metaDescription: "Govern wage orders, workplace-safety directives and employment rulings as certified, permanently verifiable Official Records. One authoritative order and dispute-ready evidence for labour authorities.",
  },
  {
    slug: "food-safety",
    name: "Food Safety & Agriculture",
    forLabel: "for Food-Safety & Agriculture Authorities",
    banner: "food-safety",
    headline: "Govern food-safety alerts, standards and recall notices as Official Records.",
    intro:
      "A food-safety alert must reach the public as the genuine, current notice — lives depend on it. Sovereign Dispatch governs every alert, standard and recall notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Food-Safety Alerts", "Agricultural Standards", "Recall Notices", "Inspection Determinations", "Import & Quarantine Rules", "Public Guidance"],
    authorities: ["Director of Food Safety", "Chief Veterinary / Agronomy Officer", "Head of Inspection", "Legal Counsel", "Standards Authority"],
    problems: [
      { t: "Alerts the public can trust", d: "A circulating alert cannot prove it is genuine and current. Every Dispatch alert carries a permanent Record ID anyone can verify — with no account." },
      { t: "Recalls provably governed", d: "When a recall is questioned, the authority must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every investigation", d: "When an outbreak is investigated, the chain of alerts and determinations already exists as a record." },
    ],
    frameworks: ["Codex-aligned food standards", "ISO 27001-aligned controls", "Traceability requirements", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Food Safety — Govern Alerts, Standards & Recalls",
    metaDescription: "Govern food-safety alerts, agricultural standards and recall notices as certified, permanently verifiable Official Records. Trustworthy alerts and investigation-ready evidence for food-safety authorities.",
  },
  {
    slug: "telecom-regulators",
    name: "Telecom Regulators",
    forLabel: "for Telecommunications Regulators",
    banner: "telecom-regulators",
    headline: "Govern spectrum licences, rules and decisions as Official Records.",
    intro:
      "A spectrum licence or numbering decision is a valuable right that must be provably authentic. Sovereign Dispatch governs every licence, rule and regulatory decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Spectrum Licences", "Regulatory Rules & Codes", "Numbering & Allocation Decisions", "Enforcement Notices", "Tariff Determinations", "Public Consultations"],
    authorities: ["Director General", "Head of Spectrum", "Enforcement Office", "Legal Counsel", "Regulatory Board"],
    problems: [
      { t: "Licences provable for their term", d: "A licensee must prove the right it holds. Every Dispatch licence carries a permanent Record ID anyone can verify independently — with no account." },
      { t: "Decisions that are attributable", d: "When an allocation is contested, the regulator must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every appeal", d: "When a decision is appealed, the chain of approval already exists as a record." },
    ],
    frameworks: ["ITU-aligned practice", "ISO 27001-aligned controls", "Regulatory-disclosure requirements", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Telecom Regulators — Govern Spectrum Licences & Rules",
    metaDescription: "Govern spectrum licences, regulatory rules and allocation decisions as certified, permanently verifiable Official Records. Provable licences and appeal-ready evidence for telecom regulators.",
  },
  {
    slug: "competition-authorities",
    name: "Competition Authorities",
    forLabel: "for Competition & Antitrust Authorities",
    banner: "competition-authorities",
    headline: "Govern merger rulings, decisions and guidance as Official Records.",
    intro:
      "An antitrust decision reshapes markets and is litigated for years. Sovereign Dispatch governs every merger ruling, enforcement decision and guidance note through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Merger Rulings", "Enforcement Decisions", "Market Investigation Reports", "Commitment Decisions", "Guidance Notes", "Public Notices"],
    authorities: ["Director General", "Head of Mergers", "Hearing Officers", "Legal Counsel", "Decision Board"],
    problems: [
      { t: "Decisions provable years later", d: "A merger ruling must be verifiable in subsequent litigation. Dispatch maintains a single authoritative record with a permanent Record ID; superseded versions cannot pass as current." },
      { t: "Rulings that are attributable", d: "When a decision is appealed, the authority must show who decided on what version, in what order. Approval is bound to a named office, on the record." },
      { t: "Evidence for every challenge", d: "When a ruling is reviewed by a court, the complete evidence chain already exists." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Competition-procedure practice", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Competition Authorities — Govern Merger & Enforcement Rulings",
    metaDescription: "Govern merger rulings, enforcement decisions and guidance as certified, permanently verifiable Official Records. Decisions provable years later, with a complete evidence chain for competition authorities.",
  },
  {
    slug: "data-protection",
    name: "Data-Protection Authorities",
    forLabel: "for Data-Protection Authorities",
    banner: "data-protection",
    headline: "Govern privacy decisions, guidance and enforcement as Official Records.",
    intro:
      "A privacy decision or enforcement notice sets precedent and must be provably authentic. Sovereign Dispatch governs every decision, guidance note and enforcement action through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Enforcement Decisions", "Guidance & Codes", "Adequacy & Transfer Determinations", "Breach Notices", "Certification Decisions", "Public Consultations"],
    authorities: ["Commissioner", "Head of Enforcement", "Legal Counsel", "Adjudication Office", "Policy Authority"],
    problems: [
      { t: "Decisions that set precedent provably", d: "A privacy ruling is relied on by controllers and courts. Every Dispatch decision carries a permanent Record ID anyone can verify — with no account." },
      { t: "Enforcement that is attributable", d: "When a penalty is appealed, the authority must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every appeal", d: "When a decision is challenged, the chain of approval already exists as a record." },
    ],
    frameworks: ["GDPR-aligned data handling", "ISO 27001-aligned controls", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Data-Protection Authorities — Govern Privacy Decisions",
    metaDescription: "Govern enforcement decisions, guidance and adequacy determinations as certified, permanently verifiable Official Records. Precedent provable and a complete evidence chain for data-protection authorities.",
  },
  {
    slug: "public-procurement",
    name: "Public Procurement",
    forLabel: "for Public-Procurement Authorities",
    banner: "public-procurement",
    headline: "Govern tender notices, award decisions and rulings as Official Records.",
    intro:
      "A tender notice and award decision must be provably genuine to keep public spending accountable. Sovereign Dispatch governs every notice, award and review decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Tender Notices", "Award Decisions", "Framework Agreements", "Debarment & Sanction Notices", "Review-Body Rulings", "Procurement Guidance"],
    authorities: ["Director of Procurement", "Tender Board", "Review Body", "Legal Counsel", "Compliance Office"],
    problems: [
      { t: "Awards no one can dispute the provenance of", d: "A losing bidder must be able to verify the genuine award. Every Dispatch award carries a permanent Record ID anyone can verify independently — with no account." },
      { t: "Decisions provably governed", d: "When an award is challenged, the authority must show who decided on what version, in what order. Approval is bound to a named office, on the record." },
      { t: "Audit-ready by default", d: "When an auditor reviews a procurement, the complete evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Open-contracting practice", "Anti-corruption disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Public Procurement — Govern Tender Notices & Award Decisions",
    metaDescription: "Govern tender notices, award decisions and review rulings as certified, permanently verifiable Official Records. Provable awards and audit-ready evidence for public-procurement authorities.",
  },
  {
    slug: "stock-exchanges",
    name: "Stock Exchanges",
    forLabel: "for Stock Exchanges & Market Operators",
    banner: "stock-exchanges",
    headline: "Govern listing decisions, market notices and rulings as Official Records.",
    intro:
      "A listing decision or market notice moves capital and must be provably authentic the moment it is read. Sovereign Dispatch governs every decision, notice and disciplinary ruling through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Listing Decisions", "Market Notices", "Rulebook Amendments", "Suspension & Delisting Notices", "Disciplinary Rulings", "Disclosure Determinations"],
    authorities: ["Head of Listing", "Market Operations", "Disciplinary Committee", "Legal Counsel", "Exchange Board"],
    problems: [
      { t: "Notices that must be unforgeable", d: "A fabricated market notice can move prices. Every Dispatch notice carries a permanent Record ID any participant can verify — with no account." },
      { t: "Decisions that are attributable", d: "When a delisting is contested, the exchange must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every review", d: "When a ruling is reviewed by a regulator, the complete evidence chain already exists." },
    ],
    frameworks: ["IOSCO-aligned practice", "ISO 27001-aligned controls", "Market-disclosure rules", "Financial-records retention"],
    metaTitle: "Sovereign Dispatch for Stock Exchanges — Govern Listing Decisions & Market Notices",
    metaDescription: "Govern listing decisions, market notices and disciplinary rulings as certified, permanently verifiable Official Records. Unforgeable notices and a complete evidence chain for market operators.",
  },
  {
    slug: "development-banks",
    name: "Development Banks",
    forLabel: "for Development Banks & DFIs",
    banner: "development-banks",
    headline: "Govern loan approvals, policy papers and decisions as Official Records.",
    intro:
      "A development bank's approvals and policies are relied on by governments and co-financiers for decades. Sovereign Dispatch governs every approval, policy and board decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Loan & Grant Approvals", "Operational Policies", "Board Resolutions", "Safeguard Determinations", "Procurement Notices", "Disclosure Documents"],
    authorities: ["President", "Board of Directors", "Head of Operations", "Legal Counsel", "Disclosure Office"],
    problems: [
      { t: "Approvals provable to co-financiers", d: "A co-financier must verify the genuine approval and its conditions. Every Dispatch approval carries a permanent Record ID anyone can verify — with no account." },
      { t: "Decisions bound to the board", d: "A policy must hold across leadership changes. Dispatch binds issuance to the office, so authority is durable." },
      { t: "Evidence for every review", d: "When an operation is evaluated, the chain of approval and the exact version already exist as a record." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Multilateral disclosure policy", "Safeguard frameworks", "Financial-records retention"],
    metaTitle: "Sovereign Dispatch for Development Banks — Govern Loan Approvals & Policies",
    metaDescription: "Govern loan approvals, operational policies and board decisions as certified, permanently verifiable Official Records. Provable approvals and a complete evidence chain for development banks.",
  },
  {
    slug: "railway-authorities",
    name: "Railway Authorities",
    forLabel: "for Railway & Transit Authorities",
    banner: "railway-authorities",
    headline: "Govern safety directives, timetable orders and rules as Official Records.",
    intro:
      "A railway safety directive must be the authentic, current version on every line. Sovereign Dispatch governs every directive, order and rule through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Safety Directives", "Operating Rules", "Timetable & Service Orders", "Licensing Decisions", "Incident Notices", "Engineering Standards"],
    authorities: ["Director of Railways", "Chief Safety Officer", "Operations Authority", "Legal Counsel", "Standards Office"],
    problems: [
      { t: "Only the current rule may run", d: "A superseded operating rule risks lives. Dispatch keeps one authoritative version; revoked rules cannot pass as current." },
      { t: "Directives provably governed", d: "When a safety directive is reviewed, the authority must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every investigation", d: "When an incident is investigated, the complete evidence chain already exists." },
    ],
    frameworks: ["Rail-safety management practice", "ISO 27001-aligned controls", "Engineering-standards alignment", "Records retention"],
    metaTitle: "Sovereign Dispatch for Railway Authorities — Govern Safety Directives & Operating Rules",
    metaDescription: "Govern railway safety directives, operating rules and service orders as certified, permanently verifiable Official Records. One current rule and investigation-ready evidence for railway authorities.",
  },
  {
    slug: "nuclear-regulators",
    name: "Nuclear Regulators",
    forLabel: "for Nuclear & Radiation Regulators",
    banner: "nuclear-regulators",
    headline: "Govern licences, safety directives and determinations as Official Records.",
    intro:
      "In nuclear regulation, the wrong version of a licence condition or safety directive is unacceptable. Sovereign Dispatch governs every licence, directive and determination through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Operating Licences", "Safety Directives", "Inspection Determinations", "Radiation Standards", "Enforcement Notices", "Decommissioning Orders"],
    authorities: ["Director of Nuclear Safety", "Chief Inspector", "Licensing Authority", "Legal Counsel", "Technical Board"],
    problems: [
      { t: "Only the current condition governs", d: "A superseded licence condition must never be relied on. Dispatch maintains one authoritative version; revoked conditions cannot pass as official." },
      { t: "Determinations provably governed", d: "When a safety case is questioned, the regulator must show who approved it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every inquiry", d: "When an inquiry asks how a directive was issued, the complete evidence chain already exists." },
    ],
    frameworks: ["IAEA-aligned safety standards", "ISO 27001-aligned controls", "Radiation-protection frameworks", "Long-term records retention"],
    metaTitle: "Sovereign Dispatch for Nuclear Regulators — Govern Licences & Safety Directives",
    metaDescription: "Govern nuclear operating licences, safety directives and determinations as certified, permanently verifiable Official Records. One current condition and inquiry-ready evidence for nuclear regulators.",
  },
  {
    slug: "space-agencies",
    name: "Space Agencies",
    forLabel: "for Space Agencies",
    banner: "space-agencies",
    headline: "Govern mission directives, standards and decisions as Official Records.",
    intro:
      "A mission directive or technical standard must be provably the authorised version across partners and years. Sovereign Dispatch governs every directive, standard and decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Mission Directives", "Technical Standards", "Flight-Readiness Decisions", "Safety Determinations", "Frequency & Licensing Filings", "Policy Statements"],
    authorities: ["Director General", "Mission Director", "Chief Engineer", "Safety Authority", "Legal Counsel"],
    problems: [
      { t: "One authorised mission baseline", d: "A superseded directive must never drive a mission. Dispatch keeps a single authoritative version; outdated baselines cannot pass as current." },
      { t: "Readiness decisions attributable", d: "When a flight-readiness decision is reviewed, the agency must show who approved it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every review", d: "When a mission is investigated or audited, the complete evidence chain already exists." },
    ],
    frameworks: ["Mission-assurance practice", "ISO 27001-aligned controls", "International space-law filings", "Long-term records retention"],
    metaTitle: "Sovereign Dispatch for Space Agencies — Govern Mission Directives & Standards",
    metaDescription: "Govern mission directives, technical standards and flight-readiness decisions as certified, permanently verifiable Official Records. One authorised baseline and review-ready evidence for space agencies.",
  },
  {
    slug: "national-libraries",
    name: "National Libraries",
    forLabel: "for National Libraries",
    banner: "national-libraries",
    headline: "Govern legal-deposit records, catalogues and notices as Official Records.",
    intro:
      "A national library's records of what was published and deposited must be provably authentic for centuries. Sovereign Dispatch governs every legal-deposit record, bibliographic notice and policy through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Legal-Deposit Records", "Bibliographic Notices", "Cataloguing Standards", "Acquisition Decisions", "Preservation Policies", "Public Notices"],
    authorities: ["National Librarian", "Head of Legal Deposit", "Cataloguing Authority", "Legal Counsel", "Preservation Office"],
    problems: [
      { t: "Records provable for centuries", d: "A deposit record must be verifiable as authentic far into the future. Every Dispatch record carries a permanent Record ID anyone can verify — with no account." },
      { t: "Decisions that are attributable", d: "When a record is questioned, the library must show who created it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for permanence", d: "When provenance matters, the chain of record-making already exists, sealed as it was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "OAIS-aligned preservation", "Legal-deposit law", "Permanent-records retention"],
    metaTitle: "Sovereign Dispatch for National Libraries — Govern Legal Deposit & Catalogues",
    metaDescription: "Govern legal-deposit records, bibliographic notices and cataloguing standards as certified, permanently verifiable Official Records. Records provable for centuries, with a complete evidence chain.",
  },
  {
    slug: "broadcasting-authorities",
    name: "Broadcasting Authorities",
    forLabel: "for Broadcasting & Media Regulators",
    banner: "broadcasting-authorities",
    headline: "Govern licences, content rulings and codes as Official Records.",
    intro:
      "A broadcast licence and content ruling carry legal weight and are relied on by operators and the public. Sovereign Dispatch governs every licence, ruling and code through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Broadcast Licences", "Content & Standards Rulings", "Codes of Practice", "Sanction Notices", "Spectrum & Coverage Decisions", "Public Consultations"],
    authorities: ["Director General", "Head of Content Standards", "Enforcement Office", "Legal Counsel", "Regulatory Board"],
    problems: [
      { t: "Licences provable for their term", d: "A broadcaster must prove the right it holds. Every Dispatch licence carries a permanent Record ID anyone can verify — with no account." },
      { t: "Rulings that are attributable", d: "When a sanction is appealed, the authority must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every appeal", d: "When a ruling is challenged, the chain of approval already exists as a record." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Media-regulation practice", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Broadcasting Authorities — Govern Licences & Content Rulings",
    metaDescription: "Govern broadcast licences, content rulings and codes of practice as certified, permanently verifiable Official Records. Provable licences and appeal-ready evidence for media regulators.",
  },
  {
    slug: "sports-federations",
    name: "Sports Federations",
    forLabel: "for Sports Federations & Governing Bodies",
    banner: "sports-federations",
    headline: "Govern competition rulings, eligibility and decisions as Official Records.",
    intro:
      "A federation's rulings on results, eligibility and discipline must be provably authentic and final. Sovereign Dispatch governs every ruling, regulation and decision through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Competition Rulings", "Eligibility Decisions", "Disciplinary & Anti-Doping Decisions", "Regulations & Codes", "Result Ratifications", "Public Notices"],
    authorities: ["President", "Executive Board", "Disciplinary Panel", "Legal Counsel", "Competitions Office"],
    problems: [
      { t: "Rulings provable and final", d: "An eligibility or result ruling is relied on by athletes and tribunals. Every Dispatch ruling carries a permanent Record ID anyone can verify — with no account." },
      { t: "Decisions that are attributable", d: "When a sanction is appealed to arbitration, the federation must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every appeal", d: "When a decision goes to arbitration, the complete evidence chain already exists." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Sports-arbitration practice", "Anti-doping code alignment", "Records retention"],
    metaTitle: "Sovereign Dispatch for Sports Federations — Govern Rulings & Eligibility Decisions",
    metaDescription: "Govern competition rulings, eligibility and disciplinary decisions as certified, permanently verifiable Official Records. Final, provable rulings and arbitration-ready evidence for sports federations.",
  },
  {
    slug: "chambers-of-commerce",
    name: "Chambers of Commerce",
    forLabel: "for Chambers of Commerce",
    banner: "chambers-of-commerce",
    headline: "Govern certificates of origin, attestations and notices as Official Records.",
    intro:
      "A certificate of origin or attestation is relied on across borders and must be provably genuine. Sovereign Dispatch governs every certificate, attestation and member notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Certificates of Origin", "Document Attestations", "Member Resolutions", "Trade Notices", "Arbitration Awards", "Policy Statements"],
    authorities: ["President", "Secretary General", "Certification Office", "Legal Counsel", "Council"],
    problems: [
      { t: "Certificates provable across borders", d: "A customs office abroad must verify a certificate of origin. Every Dispatch certificate carries a permanent Record ID anyone can verify independently — with no account." },
      { t: "Attestations that are attributable", d: "When an attestation is questioned, the chamber must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every dispute", d: "When a certificate is challenged, the chain of issuance already exists as a record." },
    ],
    frameworks: ["ICC-aligned certification practice", "ISO 27001-aligned controls", "Cross-border verification", "Records retention"],
    metaTitle: "Sovereign Dispatch for Chambers of Commerce — Govern Certificates of Origin",
    metaDescription: "Govern certificates of origin, document attestations and member notices as certified, permanently verifiable Official Records. Certificates provable across borders for chambers of commerce.",
  },
  {
    slug: "immigration-authorities",
    name: "Immigration Authorities",
    forLabel: "for Immigration & Border Authorities",
    banner: "immigration-authorities",
    headline: "Govern visa rulings, status decisions and notices as Official Records.",
    intro:
      "A visa ruling or status decision changes lives and must be provably the genuine decision. Sovereign Dispatch governs every ruling, status decision and public notice through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Visa & Permit Decisions", "Status Determinations", "Policy Rulings", "Appeal Decisions", "Public Notices", "Operational Directives"],
    authorities: ["Director of Immigration", "Head of Casework", "Appeals Office", "Legal Counsel", "Policy Authority"],
    problems: [
      { t: "Decisions an applicant can rely on", d: "An applicant must prove the decision that was made. Dispatch maintains a single authoritative record with a permanent Record ID; superseded decisions cannot pass as current." },
      { t: "Determinations that are attributable", d: "When a status is appealed, the authority must show who decided under what delegation. Approval is bound to a named office and the exact version." },
      { t: "Audit-ready by default", d: "When a tribunal or inspector reviews a decision, the evidence chain already exists — produced as the record was made." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Applicant-data residency", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Immigration Authorities — Govern Visa & Status Decisions",
    metaDescription: "Govern visa decisions, status determinations and appeal rulings as certified, permanently verifiable Official Records. Reliable, attributable decisions and audit-ready evidence for immigration authorities.",
  },
  {
    slug: "consumer-protection",
    name: "Consumer Protection",
    forLabel: "for Consumer-Protection Agencies",
    banner: "consumer-protection",
    headline: "Govern recall notices, enforcement and guidance as Official Records.",
    intro:
      "A product-recall notice must reach the public as the genuine, current warning. Sovereign Dispatch governs every recall, enforcement action and guidance note through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Product-Recall Notices", "Enforcement Decisions", "Safety Standards", "Warning Notices", "Guidance & Codes", "Public Consultations"],
    authorities: ["Director of Consumer Protection", "Head of Enforcement", "Legal Counsel", "Standards Authority", "Adjudication Office"],
    problems: [
      { t: "Recalls the public can trust", d: "A circulating recall cannot prove it is genuine and current. Every Dispatch recall carries a permanent Record ID anyone can verify — with no account." },
      { t: "Enforcement that is attributable", d: "When a penalty is appealed, the agency must show who decided on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every challenge", d: "When an action is contested, the chain of approval already exists as a record." },
    ],
    frameworks: ["ISO 27001-aligned controls", "Product-safety regulation", "Administrative-law disclosure", "Public-records retention"],
    metaTitle: "Sovereign Dispatch for Consumer Protection — Govern Recalls & Enforcement",
    metaDescription: "Govern product-recall notices, enforcement decisions and safety standards as certified, permanently verifiable Official Records. Trustworthy recalls and challenge-ready evidence for consumer-protection agencies.",
  },
  {
    slug: "research-institutes",
    name: "Research Institutes",
    forLabel: "for Research Institutes & National Labs",
    banner: "research-institutes",
    headline: "Govern technical reports, standards and findings as Official Records.",
    intro:
      "A national lab's reports and reference standards are cited as authoritative and must be provably genuine. Sovereign Dispatch governs every report, standard and finding through an enforced approval chain and seals it as a permanently verifiable Official Record.",
    publications: ["Technical Reports", "Reference Standards", "Test & Certification Results", "Research Findings", "Methodology Notes", "Advisory Statements"],
    authorities: ["Director", "Chief Scientist", "Head of Quality", "Legal Counsel", "Publications Office"],
    problems: [
      { t: "Findings provably genuine", d: "A cited report must be verifiable as the authoritative version. Every Dispatch report carries a permanent Record ID anyone can verify — with no account." },
      { t: "Results that are attributable", d: "When a certification result is relied on, the institute must show who issued it on what version. Approval is bound to a named office, on the record." },
      { t: "Evidence for every citation", d: "When a finding is questioned, the chain of approval and the exact version already exist as a record." },
    ],
    frameworks: ["ISO/IEC 17025-aligned practice", "ISO 27001-aligned controls", "Research-integrity frameworks", "Records retention"],
    metaTitle: "Sovereign Dispatch for Research Institutes — Govern Technical Reports & Standards",
    metaDescription: "Govern technical reports, reference standards and certification results as certified, permanently verifiable Official Records. Genuine, attributable findings and a complete evidence chain for national labs.",
  },
];

export const INDUSTRIES_BASE = "/industries";
export const industryBySlug = (slug?: string): Industry | undefined =>
  INDUSTRIES.find((i) => i.slug === slug);
