// A hand-built book cover — no stock imagery. Each cover is drawn from a
// gradient and given a category-appropriate treatment (literary, academic or
// playful) with real cover depth (inset frame, vignette, spine), so a wall of
// them reads like a publisher's list rather than autogenerated tiles.

export interface BookSpec {
  title: string;
  author: string;
  from: string; // gradient start (any CSS color)
  to: string;   // gradient end
  lang?: string;
  tag?: string; // category — drives the treatment
}

type Style = "literary" | "academic" | "playful" | "classic";
function styleFor(cat?: string): Style {
  const c = (cat ?? "").toLowerCase();
  if (/child|early|kid|folk|story|colou?ring/.test(c)) return "playful";
  if (/educat|curricul|workbook|textbook|science|math|exam|assess|class|teacher|primary|reader|lesson/.test(c)) return "academic";
  if (/fiction|novel|memoir|poetry|sci|adventure|self|romance|thriller|literary/.test(c)) return "literary";
  return "classic";
}

const BookCover = ({ spec, className = "" }: { spec: BookSpec; className?: string }) => {
  const style = styleFor(spec.tag);
  return (
    <div
      className={`relative aspect-[3/4] w-full overflow-hidden rounded-r-md rounded-l-[3px] shadow-[0_18px_40px_-12px_rgba(0,0,0,0.55)] ring-1 ring-black/10 ${className}`}
      style={{ backgroundImage: `linear-gradient(150deg, ${spec.from}, ${spec.to})` }}
    >
      {/* Spine + page edge */}
      <div className="absolute inset-y-0 left-0 w-[7%] bg-gradient-to-r from-black/35 to-transparent" />
      <div className="absolute inset-y-0 left-[7%] w-[2px] bg-white/15" />
      {/* Sheen + vignette for physical depth */}
      <div className="absolute inset-0 bg-gradient-to-br from-white/15 via-transparent to-black/30" />
      <div className="absolute inset-0" style={{ background: "radial-gradient(120% 90% at 50% 30%, transparent 55%, rgba(0,0,0,0.28) 100%)" }} />
      {/* Inset designed frame */}
      <div className="pointer-events-none absolute inset-[6px] left-[10%] rounded-[2px] ring-1 ring-white/15" />

      {/* Language chip */}
      {spec.lang && (
        <span className="absolute right-1.5 top-1.5 z-10 rounded bg-black/25 px-1.5 py-0.5 text-[8px] font-semibold uppercase tracking-wide text-white/90 backdrop-blur-sm">
          {spec.lang}
        </span>
      )}

      {/* Treatment */}
      {style === "literary" && (
        <div className="absolute inset-0 flex flex-col items-center justify-center px-3 pl-[12%] text-center">
          {spec.tag && <div className="mb-2 text-[7px] font-semibold uppercase tracking-[0.22em] text-white/60">{spec.tag}</div>}
          <div className="mb-2 h-px w-7 bg-white/45" />
          <div className="line-clamp-4 font-serif text-[14px] font-bold italic leading-[1.12] text-white drop-shadow-sm">{spec.title}</div>
          <div className="absolute inset-x-0 bottom-2.5 text-[8px] font-medium uppercase tracking-[0.18em] text-white/75">{spec.author}</div>
        </div>
      )}

      {style === "academic" && (
        <div className="absolute inset-0 flex flex-col pl-[10%]">
          <div className="bg-black/25 px-2.5 py-1.5 backdrop-blur-sm">
            <div className="text-[7.5px] font-bold uppercase tracking-[0.16em] text-white/85">{spec.tag ?? "Education"}</div>
          </div>
          <div className="flex flex-1 items-center px-2.5">
            <div className="line-clamp-4 font-serif text-[13px] font-bold leading-[1.1] text-white drop-shadow-sm">{spec.title}</div>
          </div>
          <div className="flex items-center justify-between border-t border-white/20 px-2.5 py-1.5">
            <span className="text-[8px] font-medium text-white/75">{spec.author}</span>
            <span className="rounded bg-white/20 px-1 py-0.5 text-[7px] font-bold text-white">EDITION</span>
          </div>
        </div>
      )}

      {style === "playful" && (
        <>
          <div className="absolute -right-4 -top-4 h-16 w-16 rounded-full bg-white/15" />
          <div className="absolute bottom-8 right-2 h-8 w-8 rounded-full bg-white/10" />
          <div className="absolute inset-x-0 top-0 p-2.5 pl-[12%]">
            {spec.tag && <div className="text-[7.5px] font-bold uppercase tracking-[0.16em] text-white/70">{spec.tag}</div>}
            <div className="mt-1 line-clamp-4 font-serif text-[15px] font-extrabold leading-[1.05] text-white drop-shadow">{spec.title}</div>
          </div>
          <div className="absolute inset-x-0 bottom-2.5 pl-[12%] text-[8px] font-semibold uppercase tracking-wide text-white/80">{spec.author}</div>
        </>
      )}

      {style === "classic" && (
        <div className="absolute inset-x-0 bottom-0 p-2.5 pl-[12%]">
          {spec.tag && <div className="mb-1 text-[7.5px] font-semibold uppercase tracking-[0.18em] text-white/65">{spec.tag}</div>}
          <div className="line-clamp-3 font-serif text-[13px] font-bold leading-[1.05] text-white drop-shadow-sm">{spec.title}</div>
          <div className="mt-1 text-[8px] font-medium uppercase tracking-wide text-white/70">{spec.author}</div>
        </div>
      )}
    </div>
  );
};

export default BookCover;
