#!/usr/bin/env python3
"""Transform the DatabasePad pg_dump (database.sql) into a Supabase-native migration.

DatabasePad multi-tenants by prefixing schemas (prj_<id>, prj_<id>_auth, prj_<id>_storage)
and ships a hand-rolled auth layer. Supabase provides managed `auth` and `storage`
schemas and `auth.uid()`/`auth.role()`. This script:
  - moves the app schema prj_r28he79ew6gX -> public
  - drops the custom _auth / _storage objects (Supabase manages those)
  - keeps the signup trigger but retargets it onto auth.users
  - retargets the user_roles FK onto auth.users
  - drops COPY data blocks (re-seeded separately as INSERTs)
  - pins search_path on SECURITY DEFINER / plpgsql functions
"""
import re

PRJ = "prj_r28he79ew6gX"
SRC = "database.sql"
OUT = "supabase_migration.sql"

with open(SRC) as f:
    text = f.read()

lines = text.split("\n")

# Locate pg_dump object headers: a line "--", then "-- Name: ...; Type: T; Schema: S; Owner: -", then "--"
header_re = re.compile(r"^-- Name: (?P<name>.*); Type: (?P<type>[^;]*); Schema: (?P<schema>[^;]*); Owner:")

blocks = []  # list of (header_meta_or_None, list_of_lines)
i = 0
preamble = []
# capture preamble until first header
while i < len(lines):
    if (lines[i] == "--" and i + 2 < len(lines)
            and header_re.match(lines[i + 1]) and lines[i + 2] == "--"):
        break
    preamble.append(lines[i])
    i += 1

blocks.append((None, preamble))

while i < len(lines):
    if (lines[i] == "--" and i + 2 < len(lines)
            and header_re.match(lines[i + 1]) and lines[i + 2] == "--"):
        m = header_re.match(lines[i + 1])
        meta = m.groupdict()
        body = [lines[i], lines[i + 1], lines[i + 2]]
        i += 3
        while i < len(lines):
            if (lines[i] == "--" and i + 2 < len(lines)
                    and header_re.match(lines[i + 1]) and lines[i + 2] == "--"):
                break
            body.append(lines[i])
            i += 1
        blocks.append((meta, body))
    else:
        i += 1

kept = []
for meta, body in blocks:
    if meta is None:
        kept.append("\n".join(body))
        continue
    schema = meta["schema"].strip()
    typ = meta["type"].strip()

    # Drop all schema-creation statements (public/auth/storage already exist)
    if typ == "SCHEMA":
        continue
    # Drop COPY data dumps; we re-seed domains via INSERT below
    if typ == "TABLE DATA":
        continue
    # Custom auth/storage objects are managed by Supabase. Keep ONLY the
    # signup trigger (retargeted onto auth.users below).
    if schema in (f"{PRJ}_auth", f"{PRJ}_storage") and typ != "TRIGGER":
        continue

    kept.append("\n".join(body))

out = "\n".join(kept)

# --- Identifier remapping ---
out = out.replace(f'"{PRJ}_auth".users', "auth.users")
out = out.replace(f'"{PRJ}_auth".identities', "auth.identities")
out = out.replace(f'"{PRJ}_auth".auth_uid()', "auth.uid()")
out = out.replace(f'"{PRJ}_auth".role()', "auth.role()")
out = out.replace(f'"{PRJ}_auth"', "auth")
out = out.replace(f'"{PRJ}_storage"', "storage")
out = out.replace(f'"{PRJ}"', "public")
out = out.replace(f"{PRJ}_role", "authenticated")
# Tidy residual schema names left in pg_dump comment headers.
out = out.replace(f"{PRJ}_auth", "auth")
out = out.replace(f"{PRJ}_storage", "storage")
out = out.replace(PRJ, "public")

# Pin search_path on functions (dump sets search_path='' globally, so the
# unqualified table refs inside function bodies would otherwise not resolve).
out = out.replace("    AS $$", "    SET search_path = public, pg_temp\n    AS $$")

header = """-- SOVEREIGN: Supabase-native migration (ported from DatabasePad export)
-- Generated by scripts/port_to_supabase.py. App schema -> public; managed
-- auth/storage objects dropped; signup trigger retargeted onto auth.users.

"""

# Seed domains (the three rows from the original export) so the marketplace is not empty.
seed = """

-- Seed: featured domains
INSERT INTO public.domains
  (id, domain_name, tagline, description, price_usd, currency, status, category, tld,
   is_premium, is_featured, brand_color, accent_color, valuation_score, ssl_verified,
   ownership_verified, ai_brand_profile)
VALUES
  ('332109d6-943c-4e6f-9c66-21ac5f7f83c1', 'payvera.ai',
   'The sovereign fintech intelligence layer.',
   'Premium AI fintech domain engineered for next-generation payment infrastructure and sovereign treasury systems.',
   48000.00, 'USD', 'active', 'fintech', '.ai', true, true, '#00D9FF', '#7C3AED', 94, true, true,
   '{"slogan": "Move money at the speed of intelligence.", "concept": "AI-native payment orchestration platform"}'::jsonb),
  ('eeb895ca-7953-4cb6-bb44-9132377102b4', 'govmesh.ai',
   'Connecting the intelligence of nations.',
   'Sovereign-grade AI domain positioned for institutional intelligence networks and government coordination infrastructure.',
   125000.00, 'USD', 'active', 'govtech', '.ai', true, true, '#10B981', '#00D9FF', 96, true, true,
   '{"slogan": "Connecting the intelligence of nations.", "concept": "AI governance infrastructure platform"}'::jsonb),
  ('283700b7-1959-4c0e-a06c-480f0981cb85', 'neuralforge.io',
   'Where neural architectures are born.',
   'Elite AI development domain optimized for ML platforms, model marketplaces, and neural infrastructure tooling.',
   32000.00, 'USD', 'active', 'ai', '.io', true, true, '#F59E0B', '#EF4444', 91, true, true,
   '{"slogan": "Forge the intelligence layer.", "concept": "Neural network development cloud"}'::jsonb)
ON CONFLICT (id) DO NOTHING;
"""

with open(OUT, "w") as f:
    f.write(header + out + seed)

print(f"Wrote {OUT}")
# Sanity checks
leftovers = re.findall(PRJ, open(OUT).read())
print(f"Residual '{PRJ}' references: {len(leftovers)}")
