// Deliverables — turns engine output into real, downloadable artifacts the
// founder can review and send. Every builder is pure (string in / string out)
// so the same Markdown a modal previews is exactly what downloads. Documents
// are framed to a consistent, institutional standard: a confidential header,
// numbered sections, real tables, and a standing disclaimer — banker-desk
// quality, generated from the company's own data and the platform's engines.

import type { MemorandumDocument, BuyerCandidate, ValuationReport } from "@exit/engines";
import type { RiskReport } from "./diligence-intel.js";
import { downloadText, notify } from "./ui";

const money = (n?: number | null): string =>
  n == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);
const pct = (x?: number | null, digits = 0): string => (x == null ? "—" : `${(x * 100).toFixed(digits)}%`);
const slug = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);
const today = (): string => new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
const titleCase = (s: string): string => s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());

const DISCLAIMER =
  "Generated by ExitOS from the company's own data and the platform's deterministic engines. " +
  "This is decision-support, not investment, legal or tax advice. Figures are estimates and remain subject to diligence and definitive documentation.";

// ── Document framework ──────────────────────────────────────────────

export interface DocSection {
  readonly heading: string;
  readonly body?: string;
  readonly bullets?: readonly string[];
  readonly table?: { readonly headers: readonly string[]; readonly rows: ReadonlyArray<readonly string[]> };
}

function mdTable(headers: readonly string[], rows: ReadonlyArray<readonly string[]>): string[] {
  const out = [`| ${headers.join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`];
  for (const r of rows) out.push(`| ${r.join(" | ")} |`);
  return out;
}

/** Frame a set of sections into a consistent, institutional-grade document. */
export function frameDoc(opts: {
  title: string;
  subtitle?: string;
  meta?: ReadonlyArray<[string, string]>;
  sections: readonly DocSection[];
  confidential?: boolean;
}): string {
  const { title, subtitle, meta = [], sections, confidential = true } = opts;
  const lines: string[] = [`# ${title}`];
  if (subtitle) lines.push(`### ${subtitle}`);
  lines.push("");
  lines.push(`${confidential ? "**STRICTLY CONFIDENTIAL** · " : ""}Prepared by **ExitOS** · ${today()}`);
  const metaAll: Array<[string, string]> = [["Source", "Company financials + ExitOS engines"], ...meta];
  lines.push("", ...metaAll.map(([k, v]) => `- **${k}:** ${v}`), "", "---", "");
  sections.forEach((s, i) => {
    lines.push(`## ${i + 1}. ${s.heading}`, "");
    if (s.body) lines.push(s.body, "");
    if (s.bullets?.length) { for (const b of s.bullets) lines.push(`- ${b}`); lines.push(""); }
    if (s.table) { lines.push(...mdTable(s.table.headers, s.table.rows), ""); }
  });
  lines.push("---", "", `_${DISCLAIMER}_`, "");
  return lines.join("\n");
}

// ── Generated memoranda (CIM, teaser, summary, deck, DD index) ───────

/** A generated memorandum → Markdown, with the same confidential framing. */
export function docToMarkdown(doc: MemorandumDocument): string {
  const lines: string[] = [
    `# ${doc.title}`, "",
    `${doc.anonymized ? "" : "**STRICTLY CONFIDENTIAL** · "}Generated by ${doc.producedBy} · ${doc.sections.length} sections · ${doc.wordCount} words${doc.anonymized ? " · anonymized" : ""}`,
    `_${today()}_`, "", "---", "",
  ];
  for (const s of doc.sections) {
    lines.push(`## ${s.heading}`, "", s.body, "");
    for (const b of s.bullets ?? []) lines.push(`- ${b}`);
    if (s.bullets?.length) lines.push("");
    for (const t of s.tables ?? []) {
      lines.push(...mdTable(t.headers, t.rows));
      if (t.caption) lines.push("", `_${t.caption}_`);
      lines.push("");
    }
  }
  lines.push("---", "", `_${DISCLAIMER}_`, "");
  return lines.join("\n");
}

export const docFilename = (doc: MemorandumDocument): string => `${slug(doc.title)}.md`;

// ── Valuation summary ───────────────────────────────────────────────

/** A banker-grade valuation memo from the engine's ValuationReport. */
export function valuationMemo(report: ValuationReport, companyName: string): string {
  const h = report.headline;
  const conclusion =
    `We assess a strategic-buyer enterprise value of **${money(h.mid)}**, within a defensible range of ` +
    `**${money(h.low)} – ${money(h.high)}**. The midpoint blends ${report.methodologies.length} weighted ` +
    `methodologies applied to the company's reported figures, a ${report.countryAdjustment.toFixed(2)}× country ` +
    `adjustment, and ${report.premiums.length} strategic-buyer premium${report.premiums.length === 1 ? "" : "s"}.`;

  const sections: DocSection[] = [
    {
      heading: "Valuation conclusion",
      body: conclusion,
      table: {
        headers: ["Measure", "Value"],
        rows: [
          ["Low", money(h.low)],
          ["Midpoint", money(h.mid)],
          ["High", money(h.high)],
          ["Country adjustment", `${report.countryAdjustment.toFixed(2)}×`],
        ],
      },
    },
    {
      heading: "Methodology",
      body: "Each method is applied to the company's own figures and weighted by reliability for this profile. The midpoint is the weighted blend of the methods below.",
      table: {
        headers: ["Methodology", "Basis", "Multiple", "Range (low – high)", "Weight"],
        rows: report.methodologies.map((m) => [
          m.name,
          m.basis,
          m.multiple != null ? `${m.multiple.toFixed(1)}×` : "—",
          `${money(m.band.low)} – ${money(m.band.high)}`,
          pct(m.weight),
        ]),
      },
    },
  ];

  if (report.premiums.length) {
    sections.push({
      heading: "Strategic premia",
      body: "Adjustments a strategic acquirer would rationally pay above the financial-buyer baseline.",
      table: {
        headers: ["Premium", "Uplift", "Rationale"],
        rows: report.premiums.map((p) => [p.name, pct(p.pct), p.reason]),
      },
    });
  }
  if (report.notes.length) {
    sections.push({ heading: "Assumptions & notes", bullets: report.notes });
  }

  return frameDoc({
    title: "Company Valuation — Summary",
    subtitle: `${companyName} · strategic-buyer basis`,
    meta: [["Engine", `${report.meta.engine} v${report.meta.version}`], ["Report type", titleCase(report.reportType)]],
    sections,
  });
}

// ── Buyer target list ───────────────────────────────────────────────

const fitLine = (f: BuyerCandidate["fitDimensions"]): string =>
  `sector ${pct(f.sectorFit)} · model ${pct(f.modelFit)} · check ${pct(f.checkFit)} · geography ${pct(f.geographyFit)} · activity ${pct(f.activityFit)} · track record ${pct(f.historyFit)}`;

/** A full buyer target list — ranked summary table plus a profile per buyer
 *  with thesis, fit breakdown and the engine's expected outcome. */
export function buyerShortlistMemo(candidates: readonly BuyerCandidate[], projectName: string): string {
  const summary: DocSection = {
    heading: "Ranked shortlist",
    body: "Screened from the curated acquirer registry against sector, model, check-size, geography, recent activity and evidence-weighted M&A track record. Acquisition probability is the engine's likelihood; expected offer and days-to-close are drawn from each buyer's measured deal history.",
    table: {
      headers: ["#", "Buyer", "Type", "Prob.", "Expected offer", "Days to close", "Check range"],
      rows: candidates.map((c, i) => [
        String(i + 1),
        c.buyer.name,
        titleCase(c.buyer.buyerType),
        pct(c.probability),
        money(c.expectedOutcome.expectedHeadlineUsd),
        `${Math.round(c.expectedOutcome.expectedDaysToCash)}d`,
        `${money(c.estimatedCheck.low)} – ${money(c.estimatedCheck.high)}`,
      ]),
    },
  };

  const profiles: DocSection[] = candidates.map((c, i) => ({
    heading: `${i + 1}. ${c.buyer.name} — ${titleCase(c.buyer.buyerType)}`,
    bullets: [
      `**Thesis:** ${c.buyer.thesis}`,
      `**Why matched:** ${c.rationale}`,
      `**Acquisition probability:** ${pct(c.probability)} (${c.expectedOutcome.overallConfidence.tier} confidence)`,
      `**Expected outcome:** offer ${money(c.expectedOutcome.expectedHeadlineUsd)} → ${money(c.expectedOutcome.expectedClosingUsd)} expected net, ~${Math.round(c.expectedOutcome.expectedDaysToCash)} days, ${pct(c.expectedOutcome.premiumPct)} premium`,
      `**Fit:** ${fitLine(c.fitDimensions)}`,
      `**Check range:** ${money(c.estimatedCheck.low)} – ${money(c.estimatedCheck.high)}`,
      `**Sectors:** ${c.buyer.sectorsActive.map(titleCase).join(", ")}`,
      `**Geography:** ${c.buyer.geographyPreferred.length ? c.buyer.geographyPreferred.join(", ") : "Global"} · appetite ${c.buyer.appetite}`,
      `**Tracked deals:** ${c.history.totalDeals}${c.history.lastTargetName ? ` · most recent ${c.history.lastTargetName}` : ""}`,
    ],
  }));

  return frameDoc({
    title: "Buyer Target List",
    subtitle: `${projectName} · ${candidates.length} shortlisted acquirers`,
    sections: [summary, { heading: "Buyer profiles", body: "Full profile for each shortlisted acquirer." }, ...profiles],
  });
}

/** The ranked buyer shortlist → an analyst-grade CSV. */
export function buyerListCsv(candidates: readonly BuyerCandidate[]): string {
  const header = ["Rank", "Buyer", "Type", "Appetite", "Acq. probability", "Expected offer (USD)", "Expected net (USD)", "Days to close", "Premium", "Confidence", "Check low (USD)", "Check high (USD)", "Sector fit", "Geography fit", "Track-record fit", "Sectors", "Geography", "Thesis", "Rationale"];
  const q = (s: string): string => `"${s.replace(/"/g, "'")}"`;
  const rows = candidates.map((c, i) => [
    String(i + 1),
    q(c.buyer.name),
    c.buyer.buyerType,
    c.buyer.appetite,
    `${Math.round(c.probability * 100)}%`,
    String(Math.round(c.expectedOutcome.expectedHeadlineUsd)),
    String(Math.round(c.expectedOutcome.expectedClosingUsd)),
    String(Math.round(c.expectedOutcome.expectedDaysToCash)),
    `${Math.round(c.expectedOutcome.premiumPct * 100)}%`,
    c.expectedOutcome.overallConfidence.tier,
    String(c.estimatedCheck.low),
    String(c.estimatedCheck.high),
    `${Math.round(c.fitDimensions.sectorFit * 100)}%`,
    `${Math.round(c.fitDimensions.geographyFit * 100)}%`,
    `${Math.round(c.fitDimensions.historyFit * 100)}%`,
    q(c.buyer.sectorsActive.map(titleCase).join("; ")),
    q(c.buyer.geographyPreferred.length ? c.buyer.geographyPreferred.join("; ") : "Global"),
    q(c.buyer.thesis),
    q(c.rationale),
  ]);
  return [header, ...rows].map((r) => r.join(",")).join("\n") + "\n";
}

// ── Buyer introduction letter ───────────────────────────────────────

export function buyerIntroLetter(opts: {
  buyer: BuyerCandidate;
  projectName: string;
  askMid: number;
  fromName: string;
  anonymized?: boolean;
}): string {
  const { buyer, projectName, askMid, fromName, anonymized = true } = opts;
  const eo = buyer.expectedOutcome;
  return [
    `STRICTLY CONFIDENTIAL`,
    `${today()}`,
    "",
    `To:      ${buyer.buyer.name} — Corporate Development`,
    `From:    ${fromName}, via ExitOS`,
    `Re:      ${anonymized ? `${projectName} — a proprietary acquisition opportunity` : "Acquisition opportunity"}`,
    "",
    `Dear ${buyer.buyer.name} team,`,
    "",
    `We are reaching out on a confidential basis regarding ${projectName}, a proprietary opportunity we believe maps directly to your stated mandate — "${buyer.buyer.thesis}".`,
    "",
    `Why we thought of you specifically: ${buyer.rationale}`,
    "",
    `Indicative parameters:`,
    `  • Indicated enterprise value (mid): ${money(askMid)}`,
    `  • Estimated fit: ${pct(buyer.probability)} acquisition probability (${eo.overallConfidence.tier} confidence)`,
    `  • Your typical check for this profile: ${money(buyer.estimatedCheck.low)} – ${money(buyer.estimatedCheck.high)}`,
    `  • Benchmark pace from your track record: ~${Math.round(eo.expectedDaysToCash)} days announced-to-close`,
    "",
    `All identifying materials are gated behind a mutual NDA. On execution we will share the confidential information memorandum and open staged data-room access.`,
    "",
    `If this is of interest, simply reply and we will coordinate a first call at your convenience.`,
    "",
    `Best regards,`,
    fromName,
    `On behalf of the company · via ExitOS`,
    "",
  ].join("\n");
}

export const introFilename = (buyer: BuyerCandidate): string => `intro-${slug(buyer.buyer.name)}.txt`;

// ── Diligence / risk report ─────────────────────────────────────────

export function riskReportDoc(report: RiskReport): string {
  const sev = report.bySeverity;
  return frameDoc({
    title: report.title,
    subtitle: `${report.audience === "seller" ? "Seller-side" : "Buyer-side"} diligence intelligence`,
    sections: [
      { heading: "Executive summary", body: report.headline },
      {
        heading: "Severity profile",
        table: {
          headers: ["Severity", "Findings", "Value exposed"],
          rows: [
            ["High", String(sev.high), ""],
            ["Medium", String(sev.medium), ""],
            ["Low", String(sev.low), ""],
            ["**Total**", `**${sev.high + sev.medium + sev.low}**`, `**${money(report.totalImpactUsd)}**`],
          ],
        },
      },
      {
        heading: "Findings",
        bullets: report.points.map((p) => `**${p.title}** — ${p.body}`),
      },
      { heading: "Recommendation", body: report.recommendation },
    ],
  });
}

// ── Generic structured doc (for the remaining agent work products) ──

export function structuredDoc(title: string, subtitle: string, sections: readonly DocSection[]): string {
  return frameDoc({ title, subtitle, sections });
}

/** Backward-compatible simple brief, now framed and disclaimed. */
export function briefMarkdown(title: string, rows: ReadonlyArray<[string, string]>, body?: string): string {
  return frameDoc({
    title,
    sections: [{ heading: "Summary", ...(body ? { body } : {}), bullets: rows.map(([k, v]) => `**${k}:** ${v}`) }],
  });
}

// ── Send / download ─────────────────────────────────────────────────

export function sendDeliverable(filename: string, text: string): void {
  downloadText(filename, text);
  notify(`Sent · ${filename}`);
}

export function downloadDeliverable(filename: string, text: string): void {
  downloadText(filename, text);
}
