// Deliverables — turns engine output into real, downloadable artifacts the
// founder can review and send. Every builder is pure (string in / string out)
// so the same Markdown a modal previews is exactly what downloads. "Send"
// downloads the file and flips the item to a Sent state in the session.

import type { MemorandumDocument, BuyerCandidate } from "@exit/engines";
import { downloadText, notify } from "./ui";

const money = (n?: number | null): string =>
  n == null ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(n);

const slug = (s: string): string => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 48);

// ── Markdown builders ───────────────────────────────────────────────

/** A generated memorandum (CIM, teaser, summary, deck, DD index) → Markdown. */
export function docToMarkdown(doc: MemorandumDocument): string {
  const lines: string[] = [`# ${doc.title}`, "", `_Generated by ${doc.producedBy} · ${doc.sections.length} sections · ${doc.wordCount} words${doc.anonymized ? " · anonymized" : ""}_`, ""];
  for (const s of doc.sections) {
    lines.push(`## ${s.heading}`, "", s.body, "");
    for (const b of s.bullets ?? []) lines.push(`- ${b}`);
    if (s.bullets?.length) lines.push("");
    for (const t of s.tables ?? []) {
      lines.push(`| ${t.headers.join(" | ")} |`, `| ${t.headers.map(() => "---").join(" | ")} |`);
      for (const row of t.rows) lines.push(`| ${row.join(" | ")} |`);
      if (t.caption) lines.push("", `_${t.caption}_`);
      lines.push("");
    }
  }
  return lines.join("\n").trim() + "\n";
}

export const docFilename = (doc: MemorandumDocument): string => `${slug(doc.title)}.md`;

/** A buyer introduction letter — addressed, personalized from the candidate's
 *  rationale and the listing's anonymized handle. Real letter, ready to send. */
export function buyerIntroLetter(opts: {
  buyer: BuyerCandidate;
  projectName: string;
  askMid: number;
  fromName: string;
  anonymized?: boolean;
}): string {
  const { buyer, projectName, askMid, fromName, anonymized = true } = opts;
  const subject = anonymized
    ? `Introduction — ${projectName}, a proprietary acquisition opportunity`
    : `Introduction — acquisition opportunity`;
  return [
    `Subject: ${subject}`,
    `To: ${buyer.buyer.name}`,
    "",
    `Dear ${buyer.buyer.name} corporate development team,`,
    "",
    `We're reaching out on a confidential basis regarding ${projectName}, a proprietary opportunity we believe is a strong fit for your acquisition mandate.`,
    "",
    `Why you: ${buyer.rationale}`,
    "",
    `Indicative parameters:`,
    `  • Indicated value (mid): ${money(askMid)}`,
    `  • Estimated fit: ${Math.round(buyer.probability * 100)}% acquisition probability`,
    `  • Estimated check range: ${money(buyer.estimatedCheck.low)} – ${money(buyer.estimatedCheck.high)}`,
    "",
    `Materials are gated behind a mutual NDA. On execution we'll share the confidential information memorandum and open staged data-room access.`,
    "",
    `If this is of interest, reply to coordinate a first call.`,
    "",
    `Best regards,`,
    fromName,
    `via ExitOS`,
    "",
  ].join("\n");
}

export const introFilename = (buyer: BuyerCandidate): string => `intro-${slug(buyer.buyer.name)}.txt`;

/** The ranked buyer shortlist → a CSV the founder can hand to anyone. */
export function buyerListCsv(candidates: readonly BuyerCandidate[]): string {
  const header = ["Rank", "Buyer", "Type", "Acquisition probability", "Est. check low", "Est. check high", "Rationale"];
  const rows = candidates.map((c, i) => [
    String(i + 1),
    c.buyer.name,
    c.buyer.buyerType,
    `${Math.round(c.probability * 100)}%`,
    String(c.estimatedCheck.low),
    String(c.estimatedCheck.high),
    `"${c.rationale.replace(/"/g, "'")}"`,
  ]);
  return [header, ...rows].map((r) => r.join(",")).join("\n") + "\n";
}

/** A plain-text section list (used for agent work products that aren't memos). */
export function briefMarkdown(title: string, rows: ReadonlyArray<[string, string]>, body?: string): string {
  const lines = [`# ${title}`, ""];
  if (body) lines.push(body, "");
  for (const [k, v] of rows) lines.push(`- **${k}:** ${v}`);
  return lines.join("\n") + "\n";
}

// ── Send / download ─────────────────────────────────────────────────

/** Download the artifact and announce it as sent. Pages track the Sent set. */
export function sendDeliverable(filename: string, text: string): void {
  downloadText(filename, text);
  notify(`Sent · ${filename}`);
}

/** Just download (Review → Download), no Sent state change. */
export function downloadDeliverable(filename: string, text: string): void {
  downloadText(filename, text);
}
